import type { DocsManifest, DocsPage } from '../src/config/index.js';

const page = (
  path: string,
  title: string,
  description: string,
  order: number,
): DocsPage => ({
  alternates: [],
  breadcrumbs: [],
  canonicalPath: `/docs${path === '/' ? '/' : `${path}/`}`,
  canonicalUrl: `https://example.com/docs${path === '/' ? '/' : `${path}/`}`,
  contentKey: path,
  description,
  documentTitle: `${title} · Test Docs`,
  headings: [],
  id: path === '/' ? 'home' : path.slice(1).replaceAll('/', '-'),
  imagePath: path === '/' ? '/og/home.png' : `/og${path}.png`,
  imageUrl: `https://example.com/docs${path === '/' ? '/og/home.png' : `/og${path}.png`}`,
  layout: 'docs',
  locale: 'en',
  moduleStem: title.toLocaleLowerCase(),
  navigation: true,
  order,
  path,
  routeFile: `${title.toLocaleLowerCase()}.mdx`,
  section: path === '/' ? 'start' : 'components',
  sectionLabel: path === '/' ? 'Start' : 'Components',
  sidebarLabel: title,
  sourceFile: `content/${title.toLocaleLowerCase()}.mdx`,
  title,
});

export const docsManifest: DocsManifest = {
  defaultLocale: 'en',
  locales: {
    en: {
      id: 'en',
      label: 'English',
      language: 'en',
      messages: {
        closeNavigation: 'Close navigation',
        closeSearch: 'Close search',
        emptySearch: 'No documentation found.',
        language: 'Language',
        loading: 'Loading page',
        headerNavigation: 'Primary navigation',
        navigation: 'Documentation',
        navigationSidebar: 'Documentation sidebar',
        next: 'Next',
        nextDocument: 'Next document',
        onThisPage: 'On this page',
        openNavigation: 'Open navigation',
        previous: 'Previous',
        previousDocument: 'Previous document',
        search: 'Search documentation',
        searchFallback: 'Search is using the bundled fallback index.',
        searchIdle: 'Type to search documentation.',
        searchLoading: 'Searching documentation',
        searchResults: 'Search results',
      },
      openGraph: 'en_US',
    },
  },
  navigation: { en: [] },
  pages: [
    page('/', 'Home', 'Welcome.', 0),
    page('/components/button', 'Button', 'Commands and form actions.', 0),
    page('/components/card', 'Card', 'Grouped content.', 1),
  ],
  redirects: {},
  sections: [
    { id: 'start', label: 'Start', order: 0 },
    { id: 'components', label: 'Components', order: 1 },
  ],
  site: {
    basePath: '/docs',
    description: 'Test documentation.',
    favicon: '/favicon.svg',
    locale: { language: 'en', openGraph: 'en_US' },
    logo: { alt: 'Test Docs', dark: '/dark.svg', light: '/light.svg' },
    title: 'Test Docs',
    url: 'https://example.com',
  },
  theme: { default: 'dark' },
};
