// Generated by scripts/generate-showcase-stories.ts
import '../../../src/showcase/showcase.css';
import type { Meta, StoryObj } from '@storybook/react-vite';
import type { ShowcaseControlValues } from '../../../src/showcase/index.js';
import {
  getShowcaseControlArgs,
  getShowcaseControlArgTypes,
  mantineShowcaseEntries,
  SingleComponentStory,
} from '../../../src/showcase/index.js';

type ComponentStoryProps = ShowcaseControlValues;

const entry = (() => {
  const showcaseEntry = mantineShowcaseEntries.find(
    (candidateEntry) => candidateEntry.id === 'mantine-emptystate',
  );

  if (!showcaseEntry) {
    throw new Error('Missing showcase entry: mantine-emptystate');
  }

  return showcaseEntry;
})();

function EmptyStateStory(controlValues: ComponentStoryProps) {
  return (
    <SingleComponentStory
      controlValues={controlValues}
      entry={entry}
      library="mantine"
    />
  );
}

EmptyStateStory.displayName = 'EmptyStateStory';

const meta = {
  title: 'Mantine/EmptyState',
  component: EmptyStateStory,
  tags: ['autodocs'],
  args: getShowcaseControlArgs(entry),
  argTypes: getShowcaseControlArgTypes(entry),
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component: entry.description,
      },
    },
  },
} satisfies Meta<typeof EmptyStateStory>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
