// Generated by scripts/generate-showcase-stories.ts
import '../../../src/showcase/showcase.css';
import type { Meta, StoryObj } from '@storybook/react-vite';
import type { ShowcaseControlValues } from '../../../src/showcase/index.js';
import {
  getShowcaseControlArgs,
  getShowcaseControlArgTypes,
  mantineShowcaseEntries,
  SingleComponentStory,
} from '../../../src/showcase/index.js';

type ComponentStoryProps = ShowcaseControlValues;

const entry = mantineShowcaseEntries.find(
  (showcaseEntry) => showcaseEntry.id === 'mantine-hovercard',
);

if (!entry) {
  throw new Error('Missing showcase entry: mantine-hovercard');
}

function HoverCardStory(controlValues: ComponentStoryProps) {
  return (
    <SingleComponentStory
      controlValues={controlValues}
      entry={entry}
      library="mantine"
    />
  );
}

HoverCardStory.displayName = 'HoverCardStory';

const meta = {
  title: 'Mantine/HoverCard',
  component: HoverCardStory,
  tags: ['autodocs'],
  args: getShowcaseControlArgs(entry),
  argTypes: getShowcaseControlArgTypes(entry),
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component: entry.description,
      },
    },
  },
} satisfies Meta<typeof HoverCardStory>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
