// Generated by scripts/generate-showcase-stories.ts
import '../../../src/showcase/showcase.css';
import type { Meta, StoryObj } from '@storybook/react-vite';
import type { ShowcaseControlValues } from '../../../src/showcase/index.js';
import {
  getShowcaseControlArgs,
  getShowcaseControlArgTypes,
  mantineShowcaseEntries,
  SingleComponentStory,
} from '../../../src/showcase/index.js';

type ComponentStoryProps = ShowcaseControlValues;

const entry = mantineShowcaseEntries.find(
  (showcaseEntry) => showcaseEntry.id === 'mantine-marquee',
);

if (!entry) {
  throw new Error('Missing showcase entry: mantine-marquee');
}

function MarqueeStory(controlValues: ComponentStoryProps) {
  return (
    <SingleComponentStory
      controlValues={controlValues}
      entry={entry}
      library="mantine"
    />
  );
}

MarqueeStory.displayName = 'MarqueeStory';

const meta = {
  title: 'Mantine/Marquee',
  component: MarqueeStory,
  tags: ['autodocs'],
  args: getShowcaseControlArgs(entry),
  argTypes: getShowcaseControlArgTypes(entry),
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component: entry.description,
      },
    },
  },
} satisfies Meta<typeof MarqueeStory>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
