// Generated by scripts/generate-showcase-stories.ts
import '../../../src/showcase/showcase.css';
import type { Meta, StoryObj } from '@storybook/react-vite';
import type { ShowcaseControlValues } from '../../../src/showcase/index.js';
import {
  getShowcaseControlArgs,
  getShowcaseControlArgTypes,
  mantineShowcaseEntries,
  SingleComponentStory,
} from '../../../src/showcase/index.js';

type ComponentStoryProps = ShowcaseControlValues;

const entry = (() => {
  const showcaseEntry = mantineShowcaseEntries.find(
    (candidateEntry) => candidateEntry.id === 'mantine-numberinput',
  );

  if (!showcaseEntry) {
    throw new Error('Missing showcase entry: mantine-numberinput');
  }

  return showcaseEntry;
})();

function NumberInputStory(controlValues: ComponentStoryProps) {
  return (
    <SingleComponentStory
      controlValues={controlValues}
      entry={entry}
      library="mantine"
    />
  );
}

NumberInputStory.displayName = 'NumberInputStory';

const meta = {
  title: 'Mantine/NumberInput',
  component: NumberInputStory,
  tags: ['autodocs'],
  args: getShowcaseControlArgs(entry),
  argTypes: getShowcaseControlArgTypes(entry),
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component: entry.description,
      },
    },
  },
} satisfies Meta<typeof NumberInputStory>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
