// Generated by scripts/generate-showcase-stories.mjs
import '../../../src/showcase/showcase.css';
import type { Meta, StoryObj } from '@storybook/react-vite';
import type { ShowcaseStoryKind } from '../../../src/showcase/index.js';
import {
  mantineShowcaseEntries,
  SingleShowcaseStory,
} from '../../../src/showcase/index.js';

type ComponentStoryProps = {
  storyKind?: ShowcaseStoryKind;
};

const entry = mantineShowcaseEntries.find(
  (showcaseEntry) => showcaseEntry.id === 'mantine-stack',
);

if (!entry) {
  throw new Error('Missing showcase entry: mantine-stack');
}

function StackStory({ storyKind = 'default' }: ComponentStoryProps) {
  return <SingleShowcaseStory entry={entry} library="mantine" storyKind={storyKind} />;
}

const meta = {
  title: 'Mantine/Stack',
  component: StackStory,
  tags: ['autodocs'],
  args: {
    storyKind: 'default',
  },
  argTypes: {
    storyKind: {
      control: 'select',
      options: ['default'],
      description: 'Switch between component stories.',
    },
  },
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component: entry.description,
      },
    },
  },
} satisfies Meta<typeof StackStory>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    storyKind: 'default',
  },
};
