import { describe, expect, it } from 'vitest';
import { daisyUiShowcaseEntries } from '../daisyui-showcase.js';
import { mantineShowcaseEntries } from '../mantine-showcase.js';

const requiredDaisyUiComponents = [
  'alert',
  'avatar',
  'badge',
  'breadcrumbs',
  'button',
  'calendar',
  'card',
  'carousel',
  'chat',
  'checkbox',
  'collapse',
  'countdown',
  'diff',
  'divider',
  'dock',
  'drawer',
  'dropdown',
  'fab',
  'fieldset',
  'fileinput',
  'filter',
  'footer',
  'hero',
  'hover3d',
  'hovergallery',
  'indicator',
  'input',
  'kbd',
  'label',
  'link',
  'list',
  'loading',
  'mask',
  'menu',
  'mockup',
  'modal',
  'navbar',
  'progress',
  'radialprogress',
  'radio',
  'range',
  'rating',
  'select',
  'skeleton',
  'stack',
  'stat',
  'status',
  'steps',
  'swap',
  'tab',
  'table',
  'textarea',
  'textrotate',
  'timeline',
  'toast',
  'toggle',
  'tooltip',
  'validator',
] as const;

const requiredMantineComponents = [
  'Accordion',
  'ActionIcon',
  'Affix',
  'Alert',
  'Anchor',
  'AppShell',
  'AspectRatio',
  'Autocomplete',
  'Avatar',
  'BackgroundImage',
  'Badge',
  'Blockquote',
  'Box',
  'Breadcrumbs',
  'Burger',
  'Button',
  'Card',
  'Center',
  'Checkbox',
  'Chip',
  'Code',
  'Collapse',
  'ColorInput',
  'ColorPicker',
  'ColorSwatch',
  'Combobox',
  'Container',
  'CopyButton',
  'DataList',
  'Dialog',
  'Divider',
  'Drawer',
  'EmptyState',
  'Fieldset',
  'FileInput',
  'Flex',
  'Grid',
  'Group',
  'Highlight',
  'HoverCard',
  'Image',
  'Indicator',
  'Input',
  'JsonInput',
  'Kbd',
  'List',
  'Loader',
  'LoadingOverlay',
  'Mark',
  'Marquee',
  'Menu',
  'Modal',
  'MultiSelect',
  'NativeSelect',
  'NavLink',
  'Notification',
  'NumberFormatter',
  'NumberInput',
  'Overlay',
  'Pagination',
  'Paper',
  'PasswordInput',
  'Pill',
  'PillsInput',
  'PinInput',
  'Popover',
  'Progress',
  'Radio',
  'RangeSlider',
  'Rating',
  'RingProgress',
  'ScrollArea',
  'SegmentedControl',
  'Select',
  'SemiCircleProgress',
  'SimpleGrid',
  'Skeleton',
  'Slider',
  'Space',
  'Spoiler',
  'Stack',
  'Stepper',
  'Switch',
  'Table',
  'Tabs',
  'TagsInput',
  'Text',
  'TextInput',
  'Textarea',
  'ThemeIcon',
  'Timeline',
  'Title',
  'Tooltip',
  'Typography',
  'UnstyledButton',
] as const;

describe('showcase registries', () => {
  it('covers every daisyUI component shipped in daisyUI 5.5', () => {
    expect(daisyUiShowcaseEntries.map((entry) => entry.name).sort()).toEqual(
      [...requiredDaisyUiComponents].sort(),
    );
  });

  it('covers Mantine core components selected for visual theme review', () => {
    expect(mantineShowcaseEntries.map((entry) => entry.name).sort()).toEqual(
      [...requiredMantineComponents].sort(),
    );
  });

  it('uses stable ids for Storybook and browser tests', () => {
    const ids = [...daisyUiShowcaseEntries, ...mantineShowcaseEntries].map(
      (entry) => entry.id,
    );
    expect(new Set(ids).size).toBe(ids.length);
    expect(ids.every((id) => /^[a-z0-9-]+$/.test(id))).toBe(true);
  });
});
