import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { daisyUiShowcaseEntries } from '../daisyui-showcase.js';
import { mantineShowcaseEntries } from '../mantine-showcase.js';

const repoRoot = process.cwd();
const GENERATED_STORY_MARKER = 'Generated by scripts/generate-showcase-stories.mjs';
const obsoleteScenarioIds = [
  'preview',
  'composition',
  'tokens',
  'accessibility',
  'playground',
] as const;
const obsoleteStoryExports = [
  'Preview',
  'Composition',
  'Tokens',
  'Accessibility',
  'Playground',
] as const;
const requiredStoryExports = ['Default'] as const;
const requiredOnboardingPages = [
  [
    'stories/welcome.stories.tsx',
    "title: 'Welcome/Start Here'",
    'data-storybook-welcome',
  ],
] as const;
const requiredDocsPages = [
  ['stories/foundations/colors.stories.tsx', "title: 'Foundations/Colors'"],
  ['stories/foundations/typography.stories.tsx', "title: 'Foundations/Typography'"],
  ['stories/foundations/spacing.stories.tsx', "title: 'Foundations/Spacing'"],
  ['stories/foundations/radius.stories.tsx', "title: 'Foundations/Radius'"],
  ['stories/foundations/shadows.stories.tsx', "title: 'Foundations/Shadows'"],
  ['stories/adapters/tailwind.stories.tsx', "title: 'Adapters/Tailwind'"],
  ['stories/adapters/daisyui.stories.tsx', "title: 'Adapters/daisyUI'"],
  ['stories/adapters/mantine.stories.tsx', "title: 'Adapters/Mantine'"],
  ['stories/adapters/astro-starlight.stories.tsx', "title: 'Adapters/Astro Starlight'"],
] as const;
const requiredDemoPages = [
  [
    'stories/demo/mantine-product-app.stories.tsx',
    "title: 'Demo/Mantine Product App'",
    'data-demo-mantine',
  ],
  [
    'stories/demo/daisyui-product-app.stories.tsx',
    "title: 'Demo/daisyUI Product App'",
    'data-demo-daisyui',
  ],
  [
    'stories/demo/starlight-docs-site.stories.tsx',
    "title: 'Demo/Starlight Docs Site'",
    'data-demo-starlight',
  ],
] as const;
const legacyManualStoryPages = [
  ['stories/daisyui/buttons.stories.tsx', "title: 'daisyUI/Buttons'"],
  ['stories/daisyui/cards.stories.tsx', "title: 'daisyUI/Cards'"],
  ['stories/mantine/buttons.stories.tsx', "title: 'Mantine/Buttons'"],
  ['stories/mantine/forms.stories.tsx', "title: 'Mantine/Forms'"],
  ['stories/tokens/colors.stories.tsx', "title: 'Tokens/Colors'"],
  ['stories/introduction.stories.tsx', "title: 'Introduction / Overview'"],
] as const;
const removedStaticStoryPages = [
  ['stories/introduction/welcome.stories.tsx', "title: 'Introduction/Welcome'"],
  ['stories/astro/starlight-theme.stories.tsx', "title: 'Astro/Starlight Theme'"],
  ['stories/environments/starlight.stories.tsx', "title: 'Environments/Starlight'"],
  [
    'stories/environments/mantine-tailwind.stories.tsx',
    "title: 'Environments/Mantine + Tailwind'",
  ],
  [
    'stories/environments/daisyui-tailwind.stories.tsx',
    "title: 'Environments/daisyUI + Tailwind'",
  ],
] as const;

function storyPath(library: 'mantine' | 'daisyui', id: string) {
  return join(repoRoot, 'stories', library, 'components', `${id}.stories.tsx`);
}

function storyPathForEntry(library: 'mantine' | 'daisyui', entry: { id: string }) {
  return storyPath(library, entry.id.replace(new RegExp(`^${library}-`), ''));
}

describe('storybook component story structure', () => {
  it('has a committed story generator script', () => {
    const packageJson = JSON.parse(
      readFileSync(join(repoRoot, 'package.json'), 'utf8'),
    );

    expect(existsSync(join(repoRoot, 'scripts/generate-showcase-stories.mjs'))).toBe(
      true,
    );
    expect(packageJson.scripts['generate:stories']).toBe(
      'node scripts/generate-showcase-stories.mjs',
    );
  });

  it('has a Storybook scenario audit script', () => {
    const packageJson = JSON.parse(
      readFileSync(join(repoRoot, 'package.json'), 'utf8'),
    );
    const auditScriptPath = join(repoRoot, 'scripts/audit-storybook-scenarios.mjs');

    expect(packageJson.scripts['storybook:audit']).toBe(
      'node scripts/audit-storybook-scenarios.mjs',
    );
    expect(existsSync(auditScriptPath)).toBe(true);

    const auditScript = readFileSync(auditScriptPath, 'utf8');

    expect(auditScript).toContain('storybook-static/index.json');
    expect(auditScript).toContain('iframe.html?id=');
    expect(auditScript).toContain('artifacts/storybook-scenario-audit/audit.json');
    expect(auditScript).toContain('STORYBOOK_AUDIT_PORT');
    expect(auditScript).toContain('61082');

    for (const suffix of [
      '--default',
      '--variants',
      '--sizes',
      '--states',
      '--examples',
      '--docs',
    ]) {
      expect(auditScript).toContain(suffix);
    }

    expect(auditScript).toContain('obsoleteScenarioSuffixes');
    expect(auditScript).toContain('readObsoleteEntries');
    expect(auditScript).toContain('obsolete generated story suffix');
    expect(auditScript).toContain('readControlContractFailures');
    expect(auditScript).toContain('requiredStaticStorySelectors');
    expect(auditScript).toContain('data-storybook-welcome');
    expect(auditScript).toContain('data-demo-mantine');
    expect(auditScript).toContain('data-demo-daisyui');
    expect(auditScript).toContain('data-demo-starlight');
    expect(auditScript).toContain('.tinyrack-demo-page');
    expect(auditScript).toContain(
      'individual story includes showcase-card gallery chrome',
    );
    expect(auditScript).toContain('generated story does not use SingleComponentStory');

    for (const scenarioId of obsoleteScenarioIds) {
      expect(auditScript).toContain(`--${scenarioId}`);
    }
  });

  it('has one Mantine story file per showcase entry', () => {
    const missing = mantineShowcaseEntries
      .map((entry) => storyPath('mantine', entry.id.replace(/^mantine-/, '')))
      .filter((path) => !existsSync(path));

    expect(missing).toEqual([]);
    for (const entry of mantineShowcaseEntries) {
      const file = readFileSync(
        storyPath('mantine', entry.id.replace(/^mantine-/, '')),
        'utf8',
      );
      expect(file).toContain(GENERATED_STORY_MARKER);
    }
  });

  it('has one daisyUI story file per showcase entry', () => {
    const missing = daisyUiShowcaseEntries
      .map((entry) => storyPath('daisyui', entry.id.replace(/^daisyui-/, '')))
      .filter((path) => !existsSync(path));

    expect(missing).toEqual([]);
    for (const entry of daisyUiShowcaseEntries) {
      const file = readFileSync(
        storyPath('daisyui', entry.id.replace(/^daisyui-/, '')),
        'utf8',
      );
      expect(file).toContain(GENERATED_STORY_MARKER);
    }
  });

  it('generates Spectrum-style component stories without universal documentation buckets', () => {
    for (const [library, entries] of [
      ['mantine', mantineShowcaseEntries],
      ['daisyui', daisyUiShowcaseEntries],
    ] as const) {
      for (const entry of entries) {
        const file = readFileSync(storyPathForEntry(library, entry), 'utf8');

        expect(file).toContain(GENERATED_STORY_MARKER);
        expect(file).toContain('tags:');
        expect(file).toContain('autodocs');

        for (const exportName of requiredStoryExports) {
          expect(file).toContain(`export const ${exportName}`);
        }

        for (const exportName of obsoleteStoryExports) {
          expect(file).not.toContain(`export const ${exportName}`);
        }

        for (const scenarioId of obsoleteScenarioIds) {
          expect(file).not.toContain(`scenarioId: '${scenarioId}'`);
        }
      }
    }
  });

  it('generates minimal component stories with registry-backed controls', () => {
    for (const [library, entries] of [
      ['mantine', mantineShowcaseEntries],
      ['daisyui', daisyUiShowcaseEntries],
    ] as const) {
      for (const entry of entries) {
        const file = readFileSync(storyPathForEntry(library, entry), 'utf8');

        expect(file).toContain('SingleComponentStory');
        expect(file).toContain('getShowcaseControlArgs(entry)');
        expect(file).toContain('getShowcaseControlArgTypes(entry)');
        expect(file).not.toContain('SingleShowcaseStory');
        expect(file).not.toContain('storyKind');
      }
    }
  });

  it('uses shallow library/component titles for generated component stories', () => {
    const mantineButtonStory = readFileSync(storyPath('mantine', 'button'), 'utf8');
    const daisyButtonStory = readFileSync(storyPath('daisyui', 'button'), 'utf8');

    expect(mantineButtonStory).toContain("title: 'Mantine/Button'");
    expect(daisyButtonStory).toContain("title: 'daisyUI/Button'");
    expect(mantineButtonStory).not.toContain('Mantine/Components/');
    expect(daisyButtonStory).not.toContain('daisyUI/Components/');
  });

  it('does not expose the old all-components bucket stories', () => {
    expect(
      existsSync(join(repoRoot, 'stories/mantine/all-components.stories.tsx')),
    ).toBe(false);
    expect(
      existsSync(join(repoRoot, 'stories/daisyui/all-components.stories.tsx')),
    ).toBe(false);
  });

  it('does not expose legacy manual aggregate/sample story pages', () => {
    for (const [relativePath, title] of legacyManualStoryPages) {
      const filePath = join(repoRoot, relativePath);

      expect(existsSync(filePath), `${relativePath} should not exist`).toBe(false);

      for (const [requiredPath] of requiredDocsPages) {
        if (existsSync(join(repoRoot, requiredPath))) {
          expect(readFileSync(join(repoRoot, requiredPath), 'utf8')).not.toContain(
            title,
          );
        }
      }
    }
  });

  it('does not expose removed static Storybook pages', () => {
    for (const [relativePath] of removedStaticStoryPages) {
      expect(
        existsSync(join(repoRoot, relativePath)),
        `${relativePath} should not exist`,
      ).toBe(false);
    }
  });

  it('uses fullscreen layout and wide showcase CSS for component stories', () => {
    const previewCss = readFileSync(
      join(repoRoot, 'src/showcase/showcase.css'),
      'utf8',
    );
    const mantineButtonStory = readFileSync(storyPath('mantine', 'button'), 'utf8');
    const daisyButtonStory = readFileSync(storyPath('daisyui', 'button'), 'utf8');

    expect(mantineButtonStory).toContain("layout: 'fullscreen'");
    expect(daisyButtonStory).toContain("layout: 'fullscreen'");
    expect(previewCss).toContain('.tinyrack-showcase-single');
    expect(previewCss).toContain('max-width: 72rem');
    expect(previewCss).toContain('width: min(100%, calc(100vw - 2rem))');
  });

  it('keeps individual component story rendering separate from gallery card chrome', () => {
    const gallerySource = readFileSync(
      join(repoRoot, 'src/showcase/gallery.tsx'),
      'utf8',
    );
    const singleShowcaseStart = gallerySource.indexOf(
      'export function SingleShowcaseStory',
    );
    const singleComponentStart = gallerySource.indexOf(
      'export function SingleComponentStory',
    );
    const galleryStart = gallerySource.indexOf('export function ShowcaseGallery');

    expect(singleShowcaseStart).toBeGreaterThanOrEqual(0);
    expect(singleComponentStart).toBeGreaterThan(singleShowcaseStart);
    expect(galleryStart).toBeGreaterThan(singleComponentStart);

    const singleShowcaseSource = gallerySource.slice(
      singleShowcaseStart,
      singleComponentStart,
    );
    const singleComponentSource = gallerySource.slice(
      singleComponentStart,
      galleryStart,
    );

    expect(singleShowcaseSource).toContain('tinyrack-showcase-single');
    expect(singleShowcaseSource).not.toContain('<ShowcaseCard');
    expect(singleShowcaseSource).not.toContain('tinyrack-showcase-card');
    expect(singleComponentSource).toContain('tinyrack-component-story');
    expect(singleComponentSource).not.toContain('<ShowcaseCard');
    expect(singleComponentSource).not.toContain('tinyrack-showcase-card');
  });

  it('has onboarding, foundations, and adapter design-system story pages', () => {
    for (const [relativePath, title, marker] of [
      ...requiredOnboardingPages,
      ...requiredDocsPages.map((page) => [...page, 'DocsPage'] as const),
    ]) {
      const filePath = join(repoRoot, relativePath);

      expect(existsSync(filePath), `${relativePath} should exist`).toBe(true);
      const file = readFileSync(filePath, 'utf8');

      expect(file).toContain(title);
      expect(file).toContain("layout: 'fullscreen'");
      expect(file).toContain(marker);
    }
  });

  it('has product-like Demo story pages for supported surfaces', () => {
    for (const [relativePath, title, marker] of requiredDemoPages) {
      const filePath = join(repoRoot, relativePath);

      expect(existsSync(filePath), `${relativePath} should exist`).toBe(true);
      const file = readFileSync(filePath, 'utf8');

      expect(file).toContain(title);
      expect(file).toContain("layout: 'fullscreen'");
      expect(file).toContain(marker);
      expect(file).toContain('tinyrack-demo-page');
    }
  });

  it('uses every registry component naturally inside product demo sections', () => {
    const mantineDemo = readFileSync(
      join(repoRoot, 'stories/demo/mantine-product-app.stories.tsx'),
      'utf8',
    );
    const daisyUiDemo = readFileSync(
      join(repoRoot, 'stories/demo/daisyui-product-app.stories.tsx'),
      'utf8',
    );
    const readDemoComponentIds = (source: string) =>
      new Set(
        [...source.matchAll(/<DemoUse\s+[^>]*\bid="([^"]+)"/g)].map(
          ([, componentId]) => componentId,
        ),
      );
    const mantineIds = readDemoComponentIds(mantineDemo);
    const daisyUiIds = readDemoComponentIds(daisyUiDemo);

    expect(mantineDemo).not.toContain('DemoComponentAudit');
    expect(mantineDemo).not.toContain('Mantine component audit');
    expect(daisyUiDemo).not.toContain('DemoComponentAudit');
    expect(daisyUiDemo).not.toContain('daisyUI component audit');

    expect(mantineIds).toEqual(
      new Set(mantineShowcaseEntries.map((entry) => entry.id)),
    );
    expect(daisyUiIds).toEqual(
      new Set(daisyUiShowcaseEntries.map((entry) => entry.id)),
    );
  });

  it('documents the Storybook component-page model', () => {
    const docsPath = join(repoRoot, 'docs/storybook-component-pages.md');

    expect(existsSync(docsPath)).toBe(true);

    const docs = readFileSync(docsPath, 'utf8');
    const readme = readFileSync(join(repoRoot, 'README.md'), 'utf8');

    expect(readme).toContain('[docs/storybook-component-pages.md]');
    expect(docs).toContain('stories/{mantine,daisyui}/components/');
    expect(docs).toContain('pnpm generate:stories');
    expect(docs).toContain('pnpm test:showcase');
    expect(docs).toContain('pnpm storybook:build');
    expect(docs).toContain('pnpm storybook:audit');

    expect(docs).toContain('Spectrum-style');
    expect(docs).toContain('Docs');
    expect(docs).toContain('Default');
    expect(docs).toContain('minimal component preview');
    expect(docs).toContain('showcase-card');
    expect(docs).toContain('args/argTypes');
    expect(docs).toContain('SingleComponentStory');
    expect(docs).toContain('Welcome/*');
    expect(docs).toContain('Demo/*');
    expect(docs).toContain('product-like Mantine, daisyUI, and Starlight pages');
    expect(docs).not.toContain('seven-scenario');
    expect(docs).not.toContain('seven scenario');
    expect(docs).not.toContain(
      'Preview / Variants / States / Composition / Tokens / Accessibility / Playground',
    );
  });

  it('orders onboarding, foundations, adapters, demos, then component catalogs', () => {
    const preview = readFileSync(join(repoRoot, '.storybook/preview.tsx'), 'utf8');
    const storySortStart = preview.indexOf('storySort');

    expect(storySortStart).toBeGreaterThanOrEqual(0);

    const storySortSource = preview.slice(storySortStart);
    const welcomeOrder = storySortSource.indexOf("'Welcome'");
    const foundationsOrder = storySortSource.indexOf("'Foundations'");
    const adaptersOrder = storySortSource.indexOf("'Adapters'");
    const demoOrder = storySortSource.indexOf("'Demo'");
    const mantineOrder = storySortSource.lastIndexOf("'Mantine'");
    const daisyUiOrder = storySortSource.lastIndexOf("'daisyUI'");

    expect(welcomeOrder).toBeGreaterThanOrEqual(0);
    expect(foundationsOrder).toBeGreaterThanOrEqual(0);
    expect(welcomeOrder).toBeLessThan(foundationsOrder);
    expect(foundationsOrder).toBeLessThan(adaptersOrder);
    expect(adaptersOrder).toBeLessThan(demoOrder);
    expect(demoOrder).toBeLessThan(mantineOrder);
    expect(demoOrder).toBeLessThan(daisyUiOrder);
    expect(foundationsOrder).toBeLessThan(mantineOrder);
    expect(foundationsOrder).toBeLessThan(daisyUiOrder);
  });

  it('includes shared docs page CSS for static Storybook documentation', () => {
    const previewCss = readFileSync(
      join(repoRoot, 'src/showcase/showcase.css'),
      'utf8',
    );

    expect(previewCss).toContain('.tinyrack-docs-page');
    expect(previewCss).toContain('.tinyrack-docs-swatch');
    expect(previewCss).toContain('.tinyrack-docs-code');
    expect(previewCss).toContain('.tinyrack-docs-data-table');
    expect(previewCss).toContain('.tinyrack-docs-callout');
    expect(previewCss).toContain('.tinyrack-demo-shell');
    expect(previewCss).toContain('.tinyrack-starlight-shell');
  });

  it('overrides Storybook canvas overflow so long and scrollable previews can scroll', () => {
    const previewCss = readFileSync(join(repoRoot, '.storybook/preview.css'), 'utf8');

    expect(previewCss).toContain('body.sb-show-main');
    expect(previewCss).toContain('overflow: auto');
    expect(previewCss).toContain('#storybook-root');
  });

  it('pins Vitest browser API away from Windows excluded port ranges', () => {
    const vitestConfig = readFileSync(join(repoRoot, 'vitest.config.ts'), 'utf8');

    expect(vitestConfig).toContain('api:');
    expect(vitestConfig).toContain("host: '127.0.0.1'");
    expect(vitestConfig).toContain('port: 61080');
  });
});
