packages:
  - packages/*

overrides:
  '@types/node': 24.13.3

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - miniflare@4.20260701.0
  - wrangler@4.107.0
  - '@types/node@24.13.3'

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
