import { tinyrackPalettes } from './colors.js';

export const tinyrackSemanticColors = {
  light: {
    canvas: tinyrackPalettes.neutral[50],
    surface: '#ffffff',
    surfaceMuted: tinyrackPalettes.neutral[100],
    surfaceHover: tinyrackPalettes.neutral[200],
    text: tinyrackPalettes.neutral[900],
    textMuted: tinyrackPalettes.neutral[600],
    border: tinyrackPalettes.neutral[300],
    borderStrong: tinyrackPalettes.neutral[500],
    focus: tinyrackPalettes.neutral[700],
    primary: tinyrackPalettes.neutral[900],
    primaryHover: tinyrackPalettes.neutral[950],
    onPrimary: tinyrackPalettes.neutral[50],
    info: tinyrackPalettes.blue[700],
    infoSurface: tinyrackPalettes.blue[50],
    infoBorder: tinyrackPalettes.blue[600],
    success: tinyrackPalettes.green[700],
    successSurface: tinyrackPalettes.green[50],
    successBorder: tinyrackPalettes.green[600],
    warning: tinyrackPalettes.amber[800],
    warningSurface: tinyrackPalettes.amber[50],
    warningBorder: tinyrackPalettes.amber[600],
    danger: tinyrackPalettes.red[700],
    dangerSurface: tinyrackPalettes.red[50],
    dangerBorder: tinyrackPalettes.red[600],
    dangerHover: tinyrackPalettes.red[800],
    onDanger: '#ffffff',
  },
  dark: {
    canvas: '#030303',
    surface: tinyrackPalettes.neutral[950],
    surfaceMuted: tinyrackPalettes.neutral[900],
    surfaceHover: tinyrackPalettes.neutral[800],
    text: tinyrackPalettes.neutral[50],
    textMuted: tinyrackPalettes.neutral[400],
    border: tinyrackPalettes.neutral[700],
    borderStrong: tinyrackPalettes.neutral[400],
    focus: tinyrackPalettes.neutral[300],
    primary: tinyrackPalettes.neutral[50],
    primaryHover: tinyrackPalettes.neutral[200],
    onPrimary: tinyrackPalettes.neutral[950],
    info: tinyrackPalettes.blue[300],
    infoSurface: tinyrackPalettes.blue[950],
    infoBorder: tinyrackPalettes.blue[400],
    success: tinyrackPalettes.green[300],
    successSurface: tinyrackPalettes.green[950],
    successBorder: tinyrackPalettes.green[400],
    warning: tinyrackPalettes.amber[300],
    warningSurface: tinyrackPalettes.amber[950],
    warningBorder: tinyrackPalettes.amber[400],
    danger: tinyrackPalettes.red[400],
    dangerSurface: tinyrackPalettes.red[950],
    dangerBorder: tinyrackPalettes.red[400],
    dangerHover: tinyrackPalettes.red[300],
    onDanger: tinyrackPalettes.red[950],
  },
} as const;
