export const componentDocCapabilities = [
  'responsive',
  'keyboard',
  'validation',
  'overflow',
  'stateful',
  'overlay',
] as const;

export type ComponentDocCapability = (typeof componentDocCapabilities)[number];

export type ComponentDocsManifestEntry = {
  capabilities: readonly ComponentDocCapability[];
  file: string;
  hasPlayground?: boolean;
  id: string;
  controls: readonly string[];
  requiredExamples: readonly string[];
  title: string;
};

export const componentDocsManifest = [
  {
    capabilities: ['responsive', 'keyboard', 'stateful'],
    file: 'app/content/en/components/accordion.mdx',
    id: 'accordion',
    controls: ['disabledItem', 'lifecycle', 'multiple', 'rootDisabled'],
    requiredExamples: ['accordion-basic', 'accordion-expansion-states'],
    title: 'Accordion',
  },
  {
    capabilities: ['responsive'],
    file: 'app/content/en/components/alert.mdx',
    id: 'alert',
    controls: ['description', 'role', 'showActions', 'title', 'variant'],
    requiredExamples: [
      'alert-basic',
      'alert-variants',
      'alert-role-recipe',
      'alert-actions',
    ],
    title: 'Alert',
  },
  {
    capabilities: ['responsive'],
    file: 'app/content/en/components/avatar.mdx',
    id: 'avatar',
    controls: ['fallback', 'imageState', 'shape', 'uiSize'],
    requiredExamples: [
      'avatar-basic',
      'avatar-image-failure',
      'avatar-size-shape-matrix',
    ],
    title: 'Avatar',
  },
  {
    capabilities: ['responsive', 'keyboard', 'overflow', 'stateful', 'overlay'],
    file: 'app/content/en/components/app-shell.mdx',
    id: 'app-shell',
    controls: [
      'breakpoint',
      'controlAppearance',
      'layout',
      'mobileSidebar',
      'sidebarMode',
    ],
    requiredExamples: ['app-shell-basic', 'app-shell-layouts'],
    title: 'AppShell',
  },
  {
    capabilities: ['responsive', 'overflow'],
    file: 'app/content/en/components/badge.mdx',
    id: 'badge',
    controls: ['children', 'icon', 'uiSize', 'variant'],
    requiredExamples: [
      'badge-basic',
      'badge-icon-and-long-label',
      'badge-size-variant-matrix',
    ],
    title: 'Badge',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'app/content/en/components/button.mdx',
    id: 'button',
    controls: [
      'appearance',
      'children',
      'disabled',
      'loading',
      'loadingLabel',
      'uiSize',
      'variant',
    ],
    requiredExamples: [
      'button-basic',
      'button-appearance-variant-matrix',
      'button-sizes',
      'button-states',
    ],
    title: 'Button',
  },
  {
    capabilities: ['responsive'],
    file: 'app/content/en/components/card.mdx',
    id: 'card',
    controls: ['content', 'description', 'footer', 'padding', 'title', 'variant'],
    requiredExamples: [
      'card-basic',
      'card-variants',
      'card-padding',
      'card-semantic-render',
      'card-edge-to-edge',
    ],
    title: 'Card',
  },
  {
    capabilities: ['responsive', 'overflow'],
    file: 'app/content/en/components/code.mdx',
    id: 'code',
    controls: ['children'],
    requiredExamples: ['code-basic', 'code-contexts'],
    title: 'Code',
  },
  {
    capabilities: ['responsive', 'overflow'],
    file: 'app/content/en/components/code-block.mdx',
    id: 'code-block',
    controls: ['code', 'language', 'wrap'],
    requiredExamples: ['code-block-basic', 'code-block-modes', 'code-block-copy'],
    title: 'Code Block',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful', 'overlay'],
    file: 'app/content/en/components/combobox.mdx',
    id: 'combobox',
    controls: [
      'autoHighlight',
      'disabled',
      'disabledOption',
      'filterMode',
      'placeholder',
      'readOnly',
    ],
    requiredExamples: [
      'combobox-basic',
      'combobox-option-states',
      'combobox-multiple-anatomy',
      'combobox-validation',
    ],
    title: 'Combobox',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful'],
    file: 'app/content/en/components/copy-button.mdx',
    id: 'copy-button',
    controls: [
      'appearance',
      'copiedLabel',
      'disabled',
      'idleLabel',
      'loading',
      'loadingLabel',
      'resetDelay',
      'uiSize',
      'unavailableLabel',
      'variant',
    ],
    requiredExamples: [
      'copy-button-basic',
      'copy-button-labels',
      'copy-button-combinations',
    ],
    title: 'CopyButton',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful'],
    file: 'app/content/en/components/collapsible.mdx',
    id: 'collapsible',
    controls: ['disabled', 'lifecycle', 'trigger'],
    requiredExamples: ['collapsible-basic', 'collapsible-lifecycle'],
    title: 'Collapsible',
  },
  {
    capabilities: ['responsive'],
    file: 'app/content/en/components/separator.mdx',
    id: 'separator',
    controls: ['decorative', 'orientation'],
    requiredExamples: [
      'separator-basic',
      'separator-orientations',
      'separator-semantics',
    ],
    title: 'Separator',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful'],
    file: 'app/content/en/components/field.mdx',
    id: 'field',
    controls: ['disabled', 'invalid', 'label', 'readOnly', 'required', 'size'],
    requiredExamples: [
      'field-basic',
      'field-field-states',
      'field-validation',
      'field-item-validity',
    ],
    title: 'Field',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'app/content/en/components/link.mdx',
    id: 'link',
    controls: ['children', 'disabled', 'underline', 'variant'],
    requiredExamples: [
      'link-basic',
      'link-variant-underline-matrix',
      'link-destinations',
    ],
    title: 'Link',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful', 'overlay'],
    file: 'app/content/en/components/menu.mdx',
    id: 'menu',
    controls: ['disabledItem'],
    requiredExamples: ['menu-basic', 'menu-item-states', 'menu-handle'],
    title: 'Menu',
  },
  {
    capabilities: ['responsive', 'keyboard', 'overflow', 'stateful', 'overlay'],
    file: 'app/content/en/components/dialog.mdx',
    id: 'dialog',
    controls: ['placement', 'title'],
    requiredExamples: [
      'dialog-basic',
      'dialog-placements',
      'dialog-handle',
      'dialog-task-form',
    ],
    title: 'Dialog',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful'],
    file: 'app/content/en/components/otp-field.mdx',
    id: 'otp-field',
    controls: ['disabled', 'length', 'readOnly'],
    requiredExamples: [
      'otp-field-basic',
      'otp-field-length-states',
      'otp-field-validation',
      'otp-field-input-flow',
    ],
    title: 'OTP Field',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful', 'overlay'],
    file: 'app/content/en/components/popover.mdx',
    id: 'popover',
    controls: ['align', 'alignOffset', 'description', 'side', 'sideOffset', 'title'],
    requiredExamples: ['popover-basic', 'popover-sides', 'popover-collision-offset'],
    title: 'Popover',
  },
  {
    capabilities: ['responsive'],
    file: 'app/content/en/components/progress.mdx',
    id: 'progress',
    controls: [
      'format',
      'indeterminate',
      'label',
      'max',
      'min',
      'uiSize',
      'value',
      'variant',
    ],
    requiredExamples: [
      'progress-basic',
      'progress-size-variant-matrix',
      'progress-values',
      'progress-custom-range',
    ],
    title: 'Progress',
  },
  {
    capabilities: ['responsive'],
    file: 'app/content/en/components/skeleton.mdx',
    id: 'skeleton',
    controls: ['animate', 'circleSize', 'height', 'shape', 'width'],
    requiredExamples: [
      'skeleton-basic',
      'skeleton-shapes',
      'skeleton-semantics',
      'skeleton-motion',
    ],
    title: 'Skeleton',
  },
  {
    capabilities: ['responsive'],
    file: 'app/content/en/components/spinner.mdx',
    id: 'spinner',
    controls: ['decorative', 'label', 'taskState', 'uiSize', 'variant'],
    requiredExamples: [
      'spinner-basic',
      'spinner-size-variant-matrix',
      'spinner-status-ownership',
      'spinner-task-lifecycle',
    ],
    title: 'Spinner',
  },
  {
    capabilities: ['responsive', 'keyboard', 'overflow'],
    file: 'app/content/en/components/table.mdx',
    id: 'table',
    controls: ['caption', 'density', 'striped'],
    requiredExamples: [
      'table-basic',
      'table-densities',
      'table-striped-footer',
      'table-overflow-empty',
    ],
    title: 'Table',
  },
  {
    capabilities: ['responsive', 'keyboard', 'overflow', 'stateful'],
    file: 'app/content/en/components/tabs.mdx',
    id: 'tabs',
    controls: ['disabledTab', 'orientation', 'uiSize'],
    requiredExamples: [
      'tabs-basic',
      'tabs-sizes',
      'tabs-vertical',
      'tabs-overflow-indicator',
    ],
    title: 'Tabs',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful', 'overlay'],
    file: 'app/content/en/components/toast.mdx',
    id: 'toast',
    controls: ['description', 'position', 'title', 'variant'],
    requiredExamples: [
      'toast-basic',
      'toast-variants',
      'toast-positions',
      'toast-lifecycle',
      'toast-anchored',
    ],
    title: 'Toast',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful', 'overlay'],
    file: 'app/content/en/components/tooltip.mdx',
    id: 'tooltip',
    controls: ['align', 'content', 'side', 'trigger'],
    requiredExamples: [
      'tooltip-basic',
      'tooltip-sides',
      'tooltip-long-content',
      'tooltip-delay-group',
    ],
    title: 'Tooltip',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful', 'overlay'],
    file: 'app/content/en/components/alert-dialog.mdx',
    id: 'alert-dialog',
    controls: ['label', 'disabled'],
    requiredExamples: ['alert-dialog-basic', 'alert-dialog-states'],
    title: 'AlertDialog',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful', 'overlay'],
    file: 'app/content/en/components/autocomplete.mdx',
    id: 'autocomplete',
    controls: [
      'autoHighlight',
      'placeholder',
      'disabled',
      'limit',
      'mode',
      'openOnInputClick',
      'readOnly',
    ],
    requiredExamples: [
      'autocomplete-basic',
      'autocomplete-states',
      'autocomplete-validation',
      'autocomplete-behaviors',
    ],
    title: 'Autocomplete',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful'],
    file: 'app/content/en/components/checkbox.mdx',
    id: 'checkbox',
    controls: ['disabled', 'indeterminate', 'label', 'readOnly', 'uiSize'],
    requiredExamples: [
      'checkbox-basic',
      'checkbox-states',
      'checkbox-validation',
      'checkbox-form-values',
    ],
    title: 'Checkbox',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful'],
    file: 'app/content/en/components/checkbox-group.mdx',
    id: 'checkbox-group',
    controls: ['disabled', 'label', 'readOnly'],
    requiredExamples: [
      'checkbox-group-basic',
      'checkbox-group-states',
      'checkbox-group-form',
      'checkbox-group-parent',
      'checkbox-group-external-form',
    ],
    title: 'Checkbox Group',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful', 'overlay'],
    file: 'app/content/en/components/context-menu.mdx',
    id: 'context-menu',
    controls: ['label', 'disabledItem', 'variant'],
    requiredExamples: ['context-menu-basic', 'context-menu-states'],
    title: 'ContextMenu',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful', 'overlay'],
    file: 'app/content/en/components/drawer.mdx',
    id: 'drawer',
    controls: ['label', 'swipeDirection'],
    requiredExamples: ['drawer-basic', 'drawer-states', 'drawer-provider-handle'],
    title: 'Drawer',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful'],
    file: 'app/content/en/components/fieldset.mdx',
    id: 'fieldset',
    controls: ['legend', 'disabled'],
    requiredExamples: ['fieldset-basic', 'fieldset-states'],
    title: 'Fieldset',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful'],
    file: 'app/content/en/components/form.mdx',
    id: 'form',
    controls: ['label', 'required', 'submitLabel'],
    requiredExamples: [
      'form-basic',
      'form-states',
      'form-server-errors',
      'form-actions',
    ],
    title: 'Form',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful'],
    file: 'app/content/en/components/input.mdx',
    id: 'input',
    controls: ['placeholder', 'disabled', 'label', 'readOnly', 'required', 'uiSize'],
    requiredExamples: ['input-basic', 'input-states', 'input-validation'],
    title: 'Input',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful'],
    file: 'app/content/en/components/icon-button.mdx',
    id: 'icon-button',
    controls: ['appearance', 'disabled', 'label', 'loading', 'uiSize', 'variant'],
    requiredExamples: ['icon-button-basic', 'icon-button-states', 'icon-button-matrix'],
    title: 'IconButton',
  },
  {
    capabilities: ['responsive', 'keyboard', 'overlay'],
    file: 'app/content/en/components/menubar.mdx',
    id: 'menubar',
    controls: ['disabled', 'orientation'],
    requiredExamples: ['menubar-basic', 'menubar-states', 'menubar-configurations'],
    title: 'Menubar',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'app/content/en/components/meter.mdx',
    id: 'meter',
    controls: ['label', 'locale', 'max', 'min', 'unit', 'value', 'variant'],
    requiredExamples: ['meter-basic', 'meter-states', 'meter-custom-range'],
    title: 'Meter',
  },
  {
    capabilities: ['responsive', 'keyboard', 'overflow', 'stateful', 'overlay'],
    file: 'app/content/en/components/navigation-menu.mdx',
    id: 'navigation-menu',
    controls: ['active', 'align', 'disabled', 'orientation', 'side'],
    requiredExamples: [
      'navigation-menu-basic',
      'navigation-menu-states',
      'navigation-menu-responsive-alternative',
    ],
    title: 'NavigationMenu',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful'],
    file: 'app/content/en/components/number-field.mdx',
    id: 'number-field',
    controls: ['label', 'disabled', 'max', 'min', 'readOnly', 'step'],
    requiredExamples: [
      'number-field-basic',
      'number-field-states',
      'number-field-validation',
      'number-field-format',
    ],
    title: 'Number Field',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful', 'overlay'],
    file: 'app/content/en/components/preview-card.mdx',
    id: 'preview-card',
    controls: ['align', 'description', 'label', 'side', 'title'],
    requiredExamples: [
      'preview-card-basic',
      'preview-card-states',
      'preview-card-positioning',
    ],
    title: 'PreviewCard',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful'],
    file: 'app/content/en/components/radio.mdx',
    id: 'radio',
    controls: ['label', 'disabled', 'readOnly', 'uiSize'],
    requiredExamples: ['radio-basic', 'radio-states'],
    title: 'Radio',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful'],
    file: 'app/content/en/components/radio-group.mdx',
    id: 'radio-group',
    controls: ['disabled', 'readOnly'],
    requiredExamples: [
      'radio-group-basic',
      'radio-group-states',
      'radio-group-validation',
      'radio-group-external-form',
    ],
    title: 'Radio Group',
  },
  {
    capabilities: ['responsive', 'keyboard', 'overflow'],
    file: 'app/content/en/components/scroll-area.mdx',
    id: 'scroll-area',
    controls: ['autoHide', 'content', 'orientation', 'variant'],
    requiredExamples: [
      'scroll-area-basic',
      'scroll-area-states',
      'scroll-area-auto-hide',
    ],
    title: 'ScrollArea',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful', 'overlay'],
    file: 'app/content/en/components/select.mdx',
    id: 'select',
    controls: ['disabled', 'disabledItem', 'readOnly', 'uiSize'],
    requiredExamples: [
      'select-basic',
      'select-states',
      'select-validation',
      'select-long-collection',
    ],
    title: 'Select',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful'],
    file: 'app/content/en/components/slider.mdx',
    id: 'slider',
    controls: ['label', 'disabled', 'orientation', 'uiSize'],
    requiredExamples: [
      'slider-basic',
      'slider-states',
      'slider-range',
      'slider-form',
      'slider-validation',
    ],
    title: 'Slider',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful'],
    file: 'app/content/en/components/switch.mdx',
    id: 'switch',
    controls: ['label', 'disabled', 'readOnly'],
    requiredExamples: ['switch-basic', 'switch-states', 'switch-validation'],
    title: 'Switch',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful'],
    file: 'app/content/en/components/toggle.mdx',
    id: 'toggle',
    controls: ['label', 'disabled'],
    requiredExamples: ['toggle-basic', 'toggle-states'],
    title: 'Toggle',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful'],
    file: 'app/content/en/components/toggle-group.mdx',
    id: 'toggle-group',
    controls: ['disabled', 'disabledItem', 'loopFocus', 'multiple', 'orientation'],
    requiredExamples: [
      'toggle-group-basic',
      'toggle-group-multiple',
      'toggle-group-orientation',
    ],
    title: 'ToggleGroup',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'app/content/en/components/toolbar.mdx',
    id: 'toolbar',
    controls: ['disabled', 'orientation'],
    requiredExamples: ['toolbar-basic', 'toolbar-states'],
    title: 'Toolbar',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful'],
    file: 'app/content/en/components/textarea.mdx',
    id: 'textarea',
    controls: ['disabled', 'label', 'placeholder', 'readOnly', 'required', 'uiSize'],
    requiredExamples: ['textarea-basic', 'textarea-states', 'textarea-validation'],
    title: 'Textarea',
  },
  {
    capabilities: ['responsive'],
    file: 'app/content/en/components/callout.mdx',
    id: 'callout',
    controls: ['children', 'title', 'variant'],
    requiredExamples: ['callout-basic'],
    title: 'Callout',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful'],
    file: 'app/content/en/components/color-scheme-toggle.mdx',
    id: 'color-scheme-toggle',
    controls: ['disabled', 'uiSize'],
    requiredExamples: ['color-scheme-toggle-basic'],
    title: 'ColorSchemeToggle',
  },
  {
    capabilities: ['responsive', 'keyboard', 'overflow', 'stateful'],
    file: 'app/content/en/components/docs-navigation.mdx',
    hasPlayground: false,
    id: 'docs-navigation',
    controls: [],
    requiredExamples: ['docs-navigation-basic'],
    title: 'DocsNavigation',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful', 'overlay'],
    file: 'app/content/en/components/docs-search.mdx',
    id: 'docs-search',
    controls: ['compact', 'disabled', 'label', 'shortcutLabel', 'uiSize'],
    requiredExamples: ['docs-search-basic'],
    title: 'DocsSearch',
  },
  {
    capabilities: ['responsive', 'keyboard', 'overflow', 'stateful', 'overlay'],
    file: 'app/content/en/components/docs-shell.mdx',
    id: 'docs-shell',
    controls: ['layout'],
    requiredExamples: ['docs-shell-basic'],
    title: 'DocsShell',
  },
  {
    capabilities: ['responsive', 'overflow'],
    file: 'app/content/en/components/document-pagination.mdx',
    id: 'document-pagination',
    controls: ['direction'],
    requiredExamples: ['document-pagination-basic'],
    title: 'DocumentPagination',
  },
  {
    capabilities: ['responsive', 'keyboard', 'overflow', 'stateful'],
    file: 'app/content/en/components/file-tree.mdx',
    hasPlayground: false,
    id: 'file-tree',
    controls: [],
    requiredExamples: ['file-tree-basic'],
    title: 'FileTree',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful', 'overlay'],
    file: 'app/content/en/components/language-select.mdx',
    id: 'language-select',
    controls: ['uiSize'],
    requiredExamples: ['language-select-basic'],
    title: 'LanguageSelect',
  },
  {
    capabilities: ['responsive'],
    file: 'app/content/en/components/steps.mdx',
    id: 'steps',
    hasPlayground: false,
    controls: [],
    requiredExamples: ['steps-basic'],
    title: 'Steps',
  },
  {
    capabilities: ['responsive', 'keyboard', 'overflow', 'stateful'],
    file: 'app/content/en/components/table-of-contents.mdx',
    id: 'table-of-contents',
    controls: ['currentHeading'],
    requiredExamples: ['table-of-contents-basic'],
    title: 'TableOfContents',
  },
] as const satisfies readonly ComponentDocsManifestEntry[];
