import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

const repoRoot = process.cwd();

const requiredDaisyUiComponents = [
  'alert',
  'avatar',
  'badge',
  'breadcrumbs',
  'button',
  'calendar',
  'card',
  'carousel',
  'chat',
  'checkbox',
  'collapse',
  'countdown',
  'diff',
  'divider',
  'dock',
  'drawer',
  'dropdown',
  'fab',
  'fieldset',
  'fileinput',
  'filter',
  'footer',
  'hero',
  'hover3d',
  'hovergallery',
  'indicator',
  'input',
  'kbd',
  'label',
  'link',
  'list',
  'loading',
  'mask',
  'menu',
  'mockup',
  'modal',
  'navbar',
  'progress',
  'radialprogress',
  'radio',
  'range',
  'rating',
  'select',
  'skeleton',
  'stack',
  'stat',
  'status',
  'steps',
  'swap',
  'tab',
  'table',
  'textarea',
  'textrotate',
  'timeline',
  'toast',
  'toggle',
  'tooltip',
  'validator',
] as const;

const requiredMantineComponents = [
  'Accordion',
  'ActionIcon',
  'Affix',
  'Alert',
  'Anchor',
  'AppShell',
  'AspectRatio',
  'Autocomplete',
  'Avatar',
  'BackgroundImage',
  'Badge',
  'Blockquote',
  'Box',
  'Breadcrumbs',
  'Burger',
  'Button',
  'Card',
  'Center',
  'Checkbox',
  'Chip',
  'Code',
  'Collapse',
  'ColorInput',
  'ColorPicker',
  'ColorSwatch',
  'Combobox',
  'Container',
  'CopyButton',
  'DataList',
  'Dialog',
  'Divider',
  'Drawer',
  'EmptyState',
  'Fieldset',
  'FileInput',
  'Flex',
  'Grid',
  'Group',
  'Highlight',
  'HoverCard',
  'Image',
  'Indicator',
  'Input',
  'JsonInput',
  'Kbd',
  'List',
  'Loader',
  'LoadingOverlay',
  'Mark',
  'Marquee',
  'Menu',
  'Modal',
  'MultiSelect',
  'NativeSelect',
  'NavLink',
  'Notification',
  'NumberFormatter',
  'NumberInput',
  'Overlay',
  'Pagination',
  'Paper',
  'PasswordInput',
  'Pill',
  'PillsInput',
  'PinInput',
  'Popover',
  'Progress',
  'Radio',
  'RangeSlider',
  'Rating',
  'RingProgress',
  'ScrollArea',
  'SegmentedControl',
  'Select',
  'SemiCircleProgress',
  'SimpleGrid',
  'Skeleton',
  'Slider',
  'Space',
  'Spoiler',
  'Stack',
  'Stepper',
  'Switch',
  'Table',
  'Tabs',
  'TagsInput',
  'Text',
  'TextInput',
  'Textarea',
  'ThemeIcon',
  'Timeline',
  'Title',
  'Tooltip',
  'Typography',
  'UnstyledButton',
] as const;

const forbiddenStorySnippets = [
  'Generated by scripts/generate-showcase-stories.ts',
  'src/showcase',
  'story-control-options',
  'selectControl(',
  'booleanControl(',
  'numberControl(',
  'rangeControl(',
  'cx(',
  'optionalModifier(',
  'SingleComponentStory',
  'ShowcaseGallery',
  'getShowcase',
  'showcaseEntry',
  'classes(',
  'modifierClass(',
  'selectControlValue(',
  'booleanControlValue(',
  'numberControlValue(',
  'selectDaisyControl(',
] as const;

function readText(path: string) {
  return readFileSync(join(repoRoot, path), 'utf8');
}

function storyPath(library: 'daisyui' | 'mantine', slug: string) {
  return join(repoRoot, 'stories', library, 'components', `${slug}.stories.tsx`);
}

function storyTitleName(name: string) {
  return name[0]?.toUpperCase() + name.slice(1);
}

function readComponentStoryFiles(library: 'daisyui' | 'mantine') {
  return readdirSync(join(repoRoot, 'stories', library, 'components'))
    .filter((file) => file.endsWith('.stories.tsx'))
    .sort();
}

function readAllComponentStories() {
  return [
    ...readComponentStoryFiles('mantine').map(
      (file) =>
        ['mantine', file, readText(`stories/mantine/components/${file}`)] as const,
    ),
    ...readComponentStoryFiles('daisyui').map(
      (file) =>
        ['daisyui', file, readText(`stories/daisyui/components/${file}`)] as const,
    ),
  ];
}

describe('manual Storybook component stories', () => {
  it('does not expose story generation scripts or ignored generated story outputs', () => {
    const packageJson = JSON.parse(readText('package.json'));
    const gitignore = readText('.gitignore');

    expect(packageJson.scripts).not.toHaveProperty('generate:stories');
    expect(existsSync(join(repoRoot, 'scripts/generate-showcase-stories.ts'))).toBe(
      false,
    );
    expect(existsSync(join(repoRoot, 'stories/story-control-options.ts'))).toBe(false);

    for (const script of Object.values(packageJson.scripts)) {
      expect(script).not.toContain('generate:stories');
      expect(script).not.toContain('generate-showcase-stories');
    }

    expect(gitignore).not.toContain('stories/daisyui/components/*.stories.tsx');
    expect(gitignore).not.toContain('stories/mantine/components/*.stories.tsx');
  });

  it('commits one manual Mantine story file for each reviewed component', () => {
    expect(readComponentStoryFiles('mantine')).toHaveLength(
      requiredMantineComponents.length,
    );

    for (const component of requiredMantineComponents) {
      const slug = component.toLowerCase();
      const path = storyPath('mantine', slug);

      expect(existsSync(path), `${slug}.stories.tsx should exist`).toBe(true);
      expect(readFileSync(path, 'utf8')).toContain(`title: 'Mantine/${component}'`);
    }
  });

  it('commits one manual daisyUI story file for each reviewed component', () => {
    expect(readComponentStoryFiles('daisyui')).toHaveLength(
      requiredDaisyUiComponents.length,
    );

    for (const component of requiredDaisyUiComponents) {
      const path = storyPath('daisyui', component);

      expect(existsSync(path), `${component}.stories.tsx should exist`).toBe(true);
      expect(readFileSync(path, 'utf8')).toContain(
        `title: 'daisyUI/${storyTitleName(component)}'`,
      );
    }
  });

  it('keeps component stories independent from showcase registries and helpers', () => {
    for (const [library, file, source] of readAllComponentStories()) {
      expect(source, `${library}/${file} should define a component`).toContain(
        'component:',
      );
      expect(source, `${library}/${file} should expose a Default story`).toContain(
        'export const Default',
      );

      for (const snippet of forbiddenStorySnippets) {
        expect(
          source,
          `${library}/${file} should not contain ${snippet}`,
        ).not.toContain(snippet);
      }
    }
  });

  it('requires every component story to expose Storybook controls', () => {
    for (const [library, file, source] of readAllComponentStories()) {
      expect(source, `${library}/${file} should type its control props`).toContain(
        'ComponentStoryProps',
      );
      expect(source, `${library}/${file} should read Storybook args`).toContain(
        'controlValues',
      );
      expect(source, `${library}/${file} should define default args`).toContain(
        'args:',
      );
      expect(source, `${library}/${file} should define Storybook controls`).toContain(
        'argTypes:',
      );
    }
  });

  it('documents manual component stories instead of generated story output', () => {
    const docs = readText('docs/storybook-component-pages.md');
    const readme = readText('README.md');

    expect(docs).toContain('Manual component stories');
    expect(docs).toContain('committed source files');
    expect(docs).not.toContain('pnpm generate:stories');
    expect(docs).not.toContain('Generated stories');
    expect(readme).toContain('committed manual component pages');
    expect(readme).not.toContain('generated-story workflow');
  });

  it('keeps the Storybook preview shell bound to the active Tinyrack theme', () => {
    const mainSource = readText('.storybook/main.ts');
    const previewSource = readText('.storybook/preview.tsx');
    const previewCss = readText('.storybook/preview.css');

    expect(mainSource).toContain('backgrounds: false');
    expect(previewSource).toContain("context.globals.theme === 'tinyrack-light'");
    expect(previewSource).toContain("context.viewMode === 'docs'");
    expect(previewSource).toContain("'tinyrack-storybook-canvas'");
    expect(previewSource).toContain("'tinyrack-storybook-docs'");
    expect(previewSource).toContain('delete document.documentElement.dataset');
    expect(previewSource).toContain('data-theme={theme}');
    expect(previewSource).toContain(
      'document.documentElement.style.colorScheme = colorScheme;',
    );
    expect(previewCss).toContain('https://fonts.gstatic.com/s/notosans/v42');
    expect(previewCss).toContain('font-family: "Noto Sans";');
    expect(previewCss).toContain('unicode-range: U+0000-024F');
    expect(previewCss).toContain('unicode-range: U+1100-11FF');
    expect(previewCss).toContain('unicode-range: U+3000-303F');
    expect(previewCss).not.toContain('font-family: "Noto Sans KR"');
    expect(previewCss).not.toContain('font-family: "Noto Sans JP"');
    expect(previewCss).toContain('#storybook-root');
    expect(previewCss).toContain('#storybook-docs');
    expect(previewCss).toContain('font-family: var(--tinyrack-font-body)');
    expect(previewCss).toContain('font-family: var(--tinyrack-font-mono)');
    expect(previewCss).toContain('.tinyrack-storybook-canvas .sb-show-main');
    expect(previewCss).toContain('.docs-story');
    expect(previewCss).toContain('background-color: var(--color-base-100);');
    expect(previewCss).toContain('color: var(--color-base-content);');
    expect(previewCss).toContain(
      'background-color: var(--tinyrack-storybook-preview-background);',
    );
    expect(previewCss).toContain('color: var(--tinyrack-storybook-preview-color);');
    expect(previewCss).not.toContain('.sbdocs-wrapper');
    expect(previewCss).not.toContain('.sbdocs-content');
  });
});
