export const componentDocCapabilities = [
  'responsive',
  'keyboard',
  'validation',
  'overflow',
  'stateful',
  'overlay',
] as const;

export type ComponentDocCapability = (typeof componentDocCapabilities)[number];

export type ComponentDocsManifestEntry = {
  capabilities: readonly ComponentDocCapability[];
  file: string;
  id: string;
  requiredControls: readonly string[];
  requiredExamples: readonly string[];
  title: string;
};

export const componentDocsManifest = [
  {
    capabilities: ['responsive', 'keyboard', 'stateful'],
    file: 'app/content/components/accordion.docs.mdx',
    id: 'accordion',
    requiredControls: [
      'disabledItem',
      'lifecycle',
      'multiple',
      'rootDisabled',
      'value',
    ],
    requiredExamples: ['accordion-basic', 'accordion-expansion-states'],
    title: 'Accordion',
  },
  {
    capabilities: ['responsive'],
    file: 'app/content/components/alert.docs.mdx',
    id: 'alert',
    requiredControls: [
      'actionMode',
      'description',
      'headingElement',
      'role',
      'title',
      'variant',
    ],
    requiredExamples: [
      'alert-basic',
      'alert-variants',
      'alert-role-recipe',
      'alert-actions',
    ],
    title: 'Alert',
  },
  {
    capabilities: ['responsive'],
    file: 'app/content/components/avatar.docs.mdx',
    id: 'avatar',
    requiredControls: ['fallback', 'imageState', 'shape', 'size'],
    requiredExamples: [
      'avatar-basic',
      'avatar-image-failure',
      'avatar-size-shape-matrix',
    ],
    title: 'Avatar',
  },
  {
    capabilities: ['responsive', 'keyboard', 'overflow', 'stateful', 'overlay'],
    file: 'app/content/components/app-shell.docs.mdx',
    id: 'app-shell',
    requiredControls: ['breakpoint', 'layout', 'open'],
    requiredExamples: ['app-shell-basic', 'app-shell-layouts'],
    title: 'AppShell',
  },
  {
    capabilities: ['responsive', 'overflow'],
    file: 'app/content/components/badge.docs.mdx',
    id: 'badge',
    requiredControls: ['children', 'icon', 'size', 'variant'],
    requiredExamples: [
      'badge-basic',
      'badge-icon-and-long-label',
      'badge-size-variant-matrix',
    ],
    title: 'Badge',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'app/content/components/button.docs.mdx',
    id: 'button',
    requiredControls: [
      'appearance',
      'children',
      'disabled',
      'loading',
      'loadingLabel',
      'size',
      'variant',
    ],
    requiredExamples: [
      'button-basic',
      'button-appearance-variant-matrix',
      'button-sizes',
      'button-states',
    ],
    title: 'Button',
  },
  {
    capabilities: ['responsive'],
    file: 'app/content/components/card.docs.mdx',
    id: 'card',
    requiredControls: [
      'content',
      'description',
      'footer',
      'padding',
      'semanticElement',
      'title',
      'variant',
    ],
    requiredExamples: [
      'card-basic',
      'card-variants',
      'card-padding',
      'card-semantic-render',
      'card-edge-to-edge',
    ],
    title: 'Card',
  },
  {
    capabilities: ['responsive', 'overflow'],
    file: 'app/content/components/code.docs.mdx',
    id: 'code',
    requiredControls: ['children', 'containerWidth'],
    requiredExamples: ['code-basic', 'code-contexts'],
    title: 'Code',
  },
  {
    capabilities: ['responsive', 'overflow'],
    file: 'app/content/components/code-block.docs.mdx',
    id: 'code-block',
    requiredControls: ['code', 'copyable', 'language', 'wrap'],
    requiredExamples: ['code-block-basic', 'code-block-modes', 'code-block-copy'],
    title: 'Code Block',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful', 'overlay'],
    file: 'app/content/components/combobox.docs.mdx',
    id: 'combobox',
    requiredControls: [
      'autoHighlight',
      'disabled',
      'disabledOption',
      'filterMode',
      'open',
      'placeholder',
      'query',
      'readOnly',
      'required',
      'selected',
    ],
    requiredExamples: [
      'combobox-basic',
      'combobox-option-states',
      'combobox-multiple-anatomy',
      'combobox-validation',
    ],
    title: 'Combobox',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful'],
    file: 'app/content/components/copy-button.docs.mdx',
    id: 'copy-button',
    requiredControls: [
      'appearance',
      'copiedLabel',
      'idleLabel',
      'resetDelay',
      'size',
      'unavailableLabel',
      'value',
      'variant',
    ],
    requiredExamples: [
      'copy-button-basic',
      'copy-button-labels',
      'copy-button-combinations',
    ],
    title: 'CopyButton',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful'],
    file: 'app/content/components/collapsible.docs.mdx',
    id: 'collapsible',
    requiredControls: ['disabled', 'lifecycle', 'open', 'trigger'],
    requiredExamples: ['collapsible-basic', 'collapsible-lifecycle'],
    title: 'Collapsible',
  },
  {
    capabilities: ['responsive'],
    file: 'app/content/components/separator.docs.mdx',
    id: 'separator',
    requiredControls: ['decorative', 'orientation'],
    requiredExamples: [
      'separator-basic',
      'separator-orientations',
      'separator-semantics',
    ],
    title: 'Separator',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful'],
    file: 'app/content/components/field.docs.mdx',
    id: 'field',
    requiredControls: [
      'disabled',
      'invalid',
      'label',
      'placeholder',
      'readOnly',
      'required',
      'size',
      'value',
    ],
    requiredExamples: [
      'field-basic',
      'field-field-states',
      'field-validation',
      'field-item-validity',
    ],
    title: 'Field',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'app/content/components/link.docs.mdx',
    id: 'link',
    requiredControls: ['children', 'destination', 'disabled', 'underline', 'variant'],
    requiredExamples: [
      'link-basic',
      'link-variant-underline-matrix',
      'link-destinations',
    ],
    title: 'Link',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful', 'overlay'],
    file: 'app/content/components/menu.docs.mdx',
    id: 'menu',
    requiredControls: ['disabledItem', 'label', 'open'],
    requiredExamples: ['menu-basic', 'menu-item-states', 'menu-handle'],
    title: 'Menu',
  },
  {
    capabilities: ['responsive', 'keyboard', 'overflow', 'stateful', 'overlay'],
    file: 'app/content/components/dialog.docs.mdx',
    id: 'dialog',
    requiredControls: ['description', 'modal', 'open', 'placement', 'size', 'title'],
    requiredExamples: [
      'dialog-basic',
      'dialog-sizes',
      'dialog-placements',
      'dialog-handle',
      'dialog-task-form',
    ],
    title: 'Dialog',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful'],
    file: 'app/content/components/otp-field.docs.mdx',
    id: 'otp-field',
    requiredControls: ['disabled', 'length', 'readOnly', 'required', 'value'],
    requiredExamples: [
      'otp-field-basic',
      'otp-field-length-states',
      'otp-field-validation',
      'otp-field-input-flow',
    ],
    title: 'OTP Field',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful', 'overlay'],
    file: 'app/content/components/popover.docs.mdx',
    id: 'popover',
    requiredControls: [
      'align',
      'alignOffset',
      'collisionMode',
      'description',
      'open',
      'side',
      'sideOffset',
      'title',
    ],
    requiredExamples: ['popover-basic', 'popover-sides', 'popover-collision-offset'],
    title: 'Popover',
  },
  {
    capabilities: ['responsive'],
    file: 'app/content/components/progress.docs.mdx',
    id: 'progress',
    requiredControls: [
      'format',
      'indeterminate',
      'label',
      'max',
      'min',
      'size',
      'value',
      'variant',
    ],
    requiredExamples: [
      'progress-basic',
      'progress-size-variant-matrix',
      'progress-values',
      'progress-custom-range',
    ],
    title: 'Progress',
  },
  {
    capabilities: ['responsive'],
    file: 'app/content/components/skeleton.docs.mdx',
    id: 'skeleton',
    requiredControls: [
      'animate',
      'announced',
      'circleSize',
      'height',
      'label',
      'shape',
      'width',
    ],
    requiredExamples: [
      'skeleton-basic',
      'skeleton-shapes',
      'skeleton-semantics',
      'skeleton-motion',
    ],
    title: 'Skeleton',
  },
  {
    capabilities: ['responsive'],
    file: 'app/content/components/spinner.docs.mdx',
    id: 'spinner',
    requiredControls: ['decorative', 'label', 'size', 'taskState', 'variant'],
    requiredExamples: [
      'spinner-basic',
      'spinner-size-variant-matrix',
      'spinner-status-ownership',
      'spinner-task-lifecycle',
    ],
    title: 'Spinner',
  },
  {
    capabilities: ['responsive', 'keyboard', 'overflow'],
    file: 'app/content/components/table.docs.mdx',
    id: 'table',
    requiredControls: ['caption', 'density', 'striped'],
    requiredExamples: [
      'table-basic',
      'table-densities',
      'table-striped-footer',
      'table-overflow-empty',
    ],
    title: 'Table',
  },
  {
    capabilities: ['responsive', 'keyboard', 'overflow', 'stateful'],
    file: 'app/content/components/tabs.docs.mdx',
    id: 'tabs',
    requiredControls: [
      'activation',
      'disabled',
      'loopFocus',
      'orientation',
      'size',
      'value',
    ],
    requiredExamples: [
      'tabs-basic',
      'tabs-sizes',
      'tabs-vertical',
      'tabs-overflow-indicator',
    ],
    title: 'Tabs',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful', 'overlay'],
    file: 'app/content/components/toast.docs.mdx',
    id: 'toast',
    requiredControls: ['description', 'initiallyOpen', 'position', 'title', 'variant'],
    requiredExamples: [
      'toast-basic',
      'toast-variants',
      'toast-positions',
      'toast-lifecycle',
      'toast-anchored',
    ],
    title: 'Toast',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful', 'overlay'],
    file: 'app/content/components/tooltip.docs.mdx',
    id: 'tooltip',
    requiredControls: [
      'align',
      'closeDelay',
      'content',
      'delay',
      'open',
      'side',
      'trigger',
      'triggerMode',
    ],
    requiredExamples: [
      'tooltip-basic',
      'tooltip-sides',
      'tooltip-long-content',
      'tooltip-delay-group',
    ],
    title: 'Tooltip',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful', 'overlay'],
    file: 'app/content/components/alert-dialog.docs.mdx',
    id: 'alert-dialog',
    requiredControls: ['label', 'open', 'disabled', 'handleMode'],
    requiredExamples: ['alert-dialog-basic', 'alert-dialog-states'],
    title: 'AlertDialog',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful', 'overlay'],
    file: 'app/content/components/autocomplete.docs.mdx',
    id: 'autocomplete',
    requiredControls: [
      'autoHighlight',
      'placeholder',
      'open',
      'disabled',
      'disabledItem',
      'mode',
      'openOnInputClick',
      'readOnly',
      'required',
      'submitOnItemClick',
      'value',
    ],
    requiredExamples: [
      'autocomplete-basic',
      'autocomplete-states',
      'autocomplete-validation',
      'autocomplete-behaviors',
    ],
    title: 'Autocomplete',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful'],
    file: 'app/content/components/checkbox.docs.mdx',
    id: 'checkbox',
    requiredControls: [
      'label',
      'checked',
      'disabled',
      'indeterminate',
      'readOnly',
      'required',
    ],
    requiredExamples: [
      'checkbox-basic',
      'checkbox-states',
      'checkbox-validation',
      'checkbox-form-values',
    ],
    title: 'Checkbox',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful'],
    file: 'app/content/components/checkbox-group.docs.mdx',
    id: 'checkbox-group',
    requiredControls: ['disabled', 'selectedValues', 'label', 'readOnly'],
    requiredExamples: [
      'checkbox-group-basic',
      'checkbox-group-states',
      'checkbox-group-form',
      'checkbox-group-parent',
      'checkbox-group-external-form',
    ],
    title: 'Checkbox Group',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful', 'overlay'],
    file: 'app/content/components/context-menu.docs.mdx',
    id: 'context-menu',
    requiredControls: ['label', 'open', 'disabledItem'],
    requiredExamples: ['context-menu-basic', 'context-menu-states'],
    title: 'ContextMenu',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful', 'overlay'],
    file: 'app/content/components/drawer.docs.mdx',
    id: 'drawer',
    requiredControls: ['activeSnapPoint', 'label', 'open', 'modal', 'swipeDirection'],
    requiredExamples: ['drawer-basic', 'drawer-states', 'drawer-provider-handle'],
    title: 'Drawer',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful'],
    file: 'app/content/components/fieldset.docs.mdx',
    id: 'fieldset',
    requiredControls: ['legend', 'disabled', 'emailAlerts'],
    requiredExamples: ['fieldset-basic', 'fieldset-states'],
    title: 'Fieldset',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful'],
    file: 'app/content/components/form.docs.mdx',
    id: 'form',
    requiredControls: ['label', 'required', 'submitLabel', 'validationMode', 'value'],
    requiredExamples: [
      'form-basic',
      'form-states',
      'form-server-errors',
      'form-actions',
    ],
    title: 'Form',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful'],
    file: 'app/content/components/input.docs.mdx',
    id: 'input',
    requiredControls: [
      'placeholder',
      'disabled',
      'label',
      'readOnly',
      'required',
      'value',
    ],
    requiredExamples: ['input-basic', 'input-states', 'input-validation'],
    title: 'Input',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful'],
    file: 'app/content/components/icon-button.docs.mdx',
    id: 'icon-button',
    requiredControls: ['appearance', 'disabled', 'label', 'loading', 'size', 'variant'],
    requiredExamples: ['icon-button-basic', 'icon-button-states', 'icon-button-matrix'],
    title: 'IconButton',
  },
  {
    capabilities: ['responsive', 'keyboard', 'overlay'],
    file: 'app/content/components/menubar.docs.mdx',
    id: 'menubar',
    requiredControls: ['disabled', 'label', 'loopFocus', 'modal', 'orientation'],
    requiredExamples: ['menubar-basic', 'menubar-states', 'menubar-configurations'],
    title: 'Menubar',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'app/content/components/meter.docs.mdx',
    id: 'meter',
    requiredControls: ['label', 'max', 'min', 'unit', 'value', 'variant'],
    requiredExamples: ['meter-basic', 'meter-states', 'meter-custom-range'],
    title: 'Meter',
  },
  {
    capabilities: ['responsive', 'keyboard', 'overflow', 'stateful', 'overlay'],
    file: 'app/content/components/navigation-menu.docs.mdx',
    id: 'navigation-menu',
    requiredControls: ['label', 'disabled', 'openSection'],
    requiredExamples: [
      'navigation-menu-basic',
      'navigation-menu-states',
      'navigation-menu-responsive-alternative',
    ],
    title: 'NavigationMenu',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful'],
    file: 'app/content/components/number-field.docs.mdx',
    id: 'number-field',
    requiredControls: [
      'label',
      'value',
      'disabled',
      'max',
      'min',
      'readOnly',
      'required',
      'step',
    ],
    requiredExamples: [
      'number-field-basic',
      'number-field-states',
      'number-field-validation',
      'number-field-format',
    ],
    title: 'Number Field',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful', 'overlay'],
    file: 'app/content/components/preview-card.docs.mdx',
    id: 'preview-card',
    requiredControls: ['align', 'closeDelay', 'delay', 'label', 'open', 'side'],
    requiredExamples: [
      'preview-card-basic',
      'preview-card-states',
      'preview-card-positioning',
    ],
    title: 'PreviewCard',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful'],
    file: 'app/content/components/radio.docs.mdx',
    id: 'radio',
    requiredControls: ['label', 'selected', 'disabled', 'readOnly'],
    requiredExamples: ['radio-basic', 'radio-states'],
    title: 'Radio',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful'],
    file: 'app/content/components/radio-group.docs.mdx',
    id: 'radio-group',
    requiredControls: ['value', 'disabled', 'readOnly', 'required'],
    requiredExamples: [
      'radio-group-basic',
      'radio-group-states',
      'radio-group-validation',
      'radio-group-external-form',
    ],
    title: 'Radio Group',
  },
  {
    capabilities: ['responsive', 'keyboard', 'overflow'],
    file: 'app/content/components/scroll-area.docs.mdx',
    id: 'scroll-area',
    requiredControls: ['content', 'orientation', 'scrollPosition', 'variant'],
    requiredExamples: ['scroll-area-basic', 'scroll-area-states'],
    title: 'ScrollArea',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful', 'overlay'],
    file: 'app/content/components/select.docs.mdx',
    id: 'select',
    requiredControls: ['open', 'disabled', 'modal', 'readOnly', 'required', 'value'],
    requiredExamples: [
      'select-basic',
      'select-states',
      'select-validation',
      'select-long-collection',
    ],
    title: 'Select',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful'],
    file: 'app/content/components/slider.docs.mdx',
    id: 'slider',
    requiredControls: ['label', 'value', 'disabled', 'orientation'],
    requiredExamples: [
      'slider-basic',
      'slider-states',
      'slider-range',
      'slider-form',
      'slider-validation',
    ],
    title: 'Slider',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful'],
    file: 'app/content/components/switch.docs.mdx',
    id: 'switch',
    requiredControls: ['label', 'checked', 'disabled', 'readOnly', 'required'],
    requiredExamples: ['switch-basic', 'switch-states', 'switch-validation'],
    title: 'Switch',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful'],
    file: 'app/content/components/toggle.docs.mdx',
    id: 'toggle',
    requiredControls: ['label', 'pressed', 'disabled'],
    requiredExamples: ['toggle-basic', 'toggle-states'],
    title: 'Toggle',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful'],
    file: 'app/content/components/toggle-group.docs.mdx',
    id: 'toggle-group',
    requiredControls: [
      'disabled',
      'itemDisabled',
      'loopFocus',
      'multiple',
      'orientation',
      'value',
    ],
    requiredExamples: [
      'toggle-group-basic',
      'toggle-group-multiple',
      'toggle-group-orientation',
    ],
    title: 'ToggleGroup',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'app/content/components/toolbar.docs.mdx',
    id: 'toolbar',
    requiredControls: ['label', 'disabled', 'loopFocus', 'orientation'],
    requiredExamples: ['toolbar-basic', 'toolbar-states'],
    title: 'Toolbar',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful'],
    file: 'app/content/components/textarea.docs.mdx',
    id: 'textarea',
    requiredControls: [
      'disabled',
      'label',
      'placeholder',
      'readOnly',
      'required',
      'value',
    ],
    requiredExamples: ['textarea-basic', 'textarea-states', 'textarea-validation'],
    title: 'Textarea',
  },
] as const satisfies readonly ComponentDocsManifestEntry[];
