export const componentDocCapabilities = [
  'responsive',
  'keyboard',
  'validation',
  'overflow',
] as const;

export type ComponentDocCapability = (typeof componentDocCapabilities)[number];

export type ComponentDocsManifestEntry = {
  capabilities: readonly ComponentDocCapability[];
  file: string;
  id: string;
  requiredControls: readonly string[];
  requiredExamples: readonly string[];
  storyId: string;
  title: string;
};

export const componentDocsManifest = [
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/accordion.docs.mdx',
    id: 'accordion',
    requiredControls: ['disabled', 'expanded', 'multiple'],
    requiredExamples: ['accordion-basic', 'accordion-expansion-states'],
    storyId: 'components-accordion--docs',
    title: 'Accordion',
  },
  {
    capabilities: ['responsive'],
    file: 'stories/components/alert.docs.mdx',
    id: 'alert',
    requiredControls: ['action', 'description', 'title', 'variant'],
    requiredExamples: ['alert-basic', 'alert-variants'],
    storyId: 'components-alert--docs',
    title: 'Alert',
  },
  {
    capabilities: ['responsive'],
    file: 'stories/components/avatar.docs.mdx',
    id: 'avatar',
    requiredControls: ['fallback', 'image', 'shape', 'size'],
    requiredExamples: ['avatar-basic', 'avatar-size-shape-matrix'],
    storyId: 'components-avatar--docs',
    title: 'Avatar',
  },
  {
    capabilities: ['responsive'],
    file: 'stories/components/badge.docs.mdx',
    id: 'badge',
    requiredControls: ['children', 'size', 'variant'],
    requiredExamples: ['badge-basic', 'badge-size-variant-matrix'],
    storyId: 'components-badge--docs',
    title: 'Badge',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/button.docs.mdx',
    id: 'button',
    requiredControls: [
      'appearance',
      'children',
      'disabled',
      'loading',
      'size',
      'variant',
    ],
    requiredExamples: [
      'button-basic',
      'button-appearance-variant-matrix',
      'button-sizes',
      'button-states',
    ],
    storyId: 'components-button--docs',
    title: 'Button',
  },
  {
    capabilities: ['responsive'],
    file: 'stories/components/card.docs.mdx',
    id: 'card',
    requiredControls: [
      'content',
      'description',
      'footer',
      'padding',
      'title',
      'variant',
    ],
    requiredExamples: ['card-basic', 'card-variants', 'card-padding'],
    storyId: 'components-card--docs',
    title: 'Card',
  },
  {
    capabilities: ['responsive', 'overflow'],
    file: 'stories/components/code.docs.mdx',
    id: 'code',
    requiredControls: ['children'],
    requiredExamples: ['code-basic', 'code-contexts'],
    storyId: 'components-code--docs',
    title: 'Code',
  },
  {
    capabilities: ['responsive', 'overflow'],
    file: 'stories/components/code-block.docs.mdx',
    id: 'code-block',
    requiredControls: ['code', 'language', 'theme', 'wrap'],
    requiredExamples: ['code-block-basic', 'code-block-modes'],
    storyId: 'components-code-block--docs',
    title: 'Code Block',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation'],
    file: 'stories/components/combobox.docs.mdx',
    id: 'combobox',
    requiredControls: ['disabled', 'disabledOption', 'open', 'placeholder', 'selected'],
    requiredExamples: ['combobox-basic', 'combobox-option-states'],
    storyId: 'components-combobox--docs',
    title: 'Combobox',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/collapsible.docs.mdx',
    id: 'collapsible',
    requiredControls: ['disabled', 'open', 'trigger'],
    requiredExamples: ['collapsible-basic', 'collapsible-states'],
    storyId: 'components-collapsible--docs',
    title: 'Collapsible',
  },
  {
    capabilities: ['responsive'],
    file: 'stories/components/separator.docs.mdx',
    id: 'separator',
    requiredControls: ['orientation'],
    requiredExamples: ['separator-basic', 'separator-orientations'],
    storyId: 'components-separator--docs',
    title: 'Separator',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation'],
    file: 'stories/components/field.docs.mdx',
    id: 'field',
    requiredControls: [
      'disabled',
      'invalid',
      'label',
      'placeholder',
      'readOnly',
      'required',
    ],
    requiredExamples: ['field-basic', 'field-field-states'],
    storyId: 'components-field--docs',
    title: 'Field',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/link.docs.mdx',
    id: 'link',
    requiredControls: ['children', 'newTab', 'underline', 'variant'],
    requiredExamples: ['link-basic', 'link-variant-underline-matrix'],
    storyId: 'components-link--docs',
    title: 'Link',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/menu.docs.mdx',
    id: 'menu',
    requiredControls: ['disabledItem', 'label', 'open'],
    requiredExamples: ['menu-basic', 'menu-item-states'],
    storyId: 'components-menu--docs',
    title: 'Menu',
  },
  {
    capabilities: ['responsive', 'keyboard', 'overflow'],
    file: 'stories/components/dialog.docs.mdx',
    id: 'dialog',
    requiredControls: ['description', 'open', 'placement', 'size', 'title'],
    requiredExamples: ['dialog-basic', 'dialog-sizes', 'dialog-placements'],
    storyId: 'components-dialog--docs',
    title: 'Dialog',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation'],
    file: 'stories/components/otp-field.docs.mdx',
    id: 'otp-field',
    requiredControls: ['disabled', 'length', 'readOnly', 'required'],
    requiredExamples: ['otp-field-basic', 'otp-field-length-states'],
    storyId: 'components-otp-field--docs',
    title: 'OTP Field',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/popover.docs.mdx',
    id: 'popover',
    requiredControls: ['align', 'description', 'open', 'side', 'title'],
    requiredExamples: ['popover-basic', 'popover-sides'],
    storyId: 'components-popover--docs',
    title: 'Popover',
  },
  {
    capabilities: ['responsive'],
    file: 'stories/components/progress.docs.mdx',
    id: 'progress',
    requiredControls: ['label', 'size', 'value', 'variant'],
    requiredExamples: [
      'progress-basic',
      'progress-size-variant-matrix',
      'progress-values',
    ],
    storyId: 'components-progress--docs',
    title: 'Progress',
  },
  {
    capabilities: ['responsive'],
    file: 'stories/components/skeleton.docs.mdx',
    id: 'skeleton',
    requiredControls: ['height', 'label', 'shape', 'width'],
    requiredExamples: ['skeleton-basic', 'skeleton-shapes'],
    storyId: 'components-skeleton--docs',
    title: 'Skeleton',
  },
  {
    capabilities: ['responsive'],
    file: 'stories/components/spinner.docs.mdx',
    id: 'spinner',
    requiredControls: ['label', 'size', 'variant'],
    requiredExamples: ['spinner-basic', 'spinner-size-variant-matrix'],
    storyId: 'components-spinner--docs',
    title: 'Spinner',
  },
  {
    capabilities: ['responsive', 'overflow'],
    file: 'stories/components/table.docs.mdx',
    id: 'table',
    requiredControls: ['caption', 'density', 'striped'],
    requiredExamples: ['table-basic', 'table-densities', 'table-striped-footer'],
    storyId: 'components-table--docs',
    title: 'Table',
  },
  {
    capabilities: ['responsive', 'keyboard', 'overflow'],
    file: 'stories/components/tabs.docs.mdx',
    id: 'tabs',
    requiredControls: ['disabled', 'orientation', 'selected', 'size'],
    requiredExamples: ['tabs-basic', 'tabs-sizes', 'tabs-orientations'],
    storyId: 'components-tabs--docs',
    title: 'Tabs',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/toast.docs.mdx',
    id: 'toast',
    requiredControls: ['description', 'initiallyOpen', 'position', 'title', 'variant'],
    requiredExamples: ['toast-basic', 'toast-variants', 'toast-positions'],
    storyId: 'components-toast--docs',
    title: 'Toast',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/tooltip.docs.mdx',
    id: 'tooltip',
    requiredControls: ['align', 'content', 'open', 'side', 'trigger'],
    requiredExamples: ['tooltip-basic', 'tooltip-sides'],
    storyId: 'components-tooltip--docs',
    title: 'Tooltip',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/alert-dialog.docs.mdx',
    id: 'alert-dialog',
    requiredControls: ['label', 'open', 'disabled'],
    requiredExamples: ['alert-dialog-basic', 'alert-dialog-states'],
    storyId: 'components-alert-dialog--docs',
    title: 'AlertDialog',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/autocomplete.docs.mdx',
    id: 'autocomplete',
    requiredControls: ['placeholder', 'open', 'disabled'],
    requiredExamples: ['autocomplete-basic', 'autocomplete-states'],
    storyId: 'components-autocomplete--docs',
    title: 'Autocomplete',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/checkbox.docs.mdx',
    id: 'checkbox',
    requiredControls: ['label', 'checked', 'disabled'],
    requiredExamples: ['checkbox-basic', 'checkbox-states'],
    storyId: 'components-checkbox--docs',
    title: 'Checkbox',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/checkbox-group.docs.mdx',
    id: 'checkbox-group',
    requiredControls: ['disabled', 'selected', 'label'],
    requiredExamples: ['checkbox-group-basic', 'checkbox-group-states'],
    storyId: 'components-checkbox-group--docs',
    title: 'CheckboxGroup',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/context-menu.docs.mdx',
    id: 'context-menu',
    requiredControls: ['label', 'open', 'disabledItem'],
    requiredExamples: ['context-menu-basic', 'context-menu-states'],
    storyId: 'components-context-menu--docs',
    title: 'ContextMenu',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/drawer.docs.mdx',
    id: 'drawer',
    requiredControls: ['label', 'open', 'modal'],
    requiredExamples: ['drawer-basic', 'drawer-states'],
    storyId: 'components-drawer--docs',
    title: 'Drawer',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/fieldset.docs.mdx',
    id: 'fieldset',
    requiredControls: ['legend', 'disabled'],
    requiredExamples: ['fieldset-basic', 'fieldset-states'],
    storyId: 'components-fieldset--docs',
    title: 'Fieldset',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/form.docs.mdx',
    id: 'form',
    requiredControls: ['label', 'required', 'submitLabel'],
    requiredExamples: ['form-basic', 'form-states'],
    storyId: 'components-form--docs',
    title: 'Form',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/input.docs.mdx',
    id: 'input',
    requiredControls: ['placeholder', 'disabled', 'readOnly', 'required'],
    requiredExamples: ['input-basic', 'input-states'],
    storyId: 'components-input--docs',
    title: 'Input',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/menubar.docs.mdx',
    id: 'menubar',
    requiredControls: ['disabled', 'orientation', 'label'],
    requiredExamples: ['menubar-basic', 'menubar-states'],
    storyId: 'components-menubar--docs',
    title: 'Menubar',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/meter.docs.mdx',
    id: 'meter',
    requiredControls: ['label', 'value'],
    requiredExamples: ['meter-basic', 'meter-states'],
    storyId: 'components-meter--docs',
    title: 'Meter',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/navigation-menu.docs.mdx',
    id: 'navigation-menu',
    requiredControls: ['label', 'disabled'],
    requiredExamples: ['navigation-menu-basic', 'navigation-menu-states'],
    storyId: 'components-navigation-menu--docs',
    title: 'NavigationMenu',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/number-field.docs.mdx',
    id: 'number-field',
    requiredControls: ['label', 'value', 'disabled'],
    requiredExamples: ['number-field-basic', 'number-field-states'],
    storyId: 'components-number-field--docs',
    title: 'NumberField',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/preview-card.docs.mdx',
    id: 'preview-card',
    requiredControls: ['label', 'open'],
    requiredExamples: ['preview-card-basic', 'preview-card-states'],
    storyId: 'components-preview-card--docs',
    title: 'PreviewCard',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/radio.docs.mdx',
    id: 'radio',
    requiredControls: ['label', 'selected', 'disabled'],
    requiredExamples: ['radio-basic', 'radio-states'],
    storyId: 'components-radio--docs',
    title: 'Radio',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/radio-group.docs.mdx',
    id: 'radio-group',
    requiredControls: ['value', 'disabled'],
    requiredExamples: ['radio-group-basic', 'radio-group-states'],
    storyId: 'components-radio-group--docs',
    title: 'RadioGroup',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/scroll-area.docs.mdx',
    id: 'scroll-area',
    requiredControls: ['content', 'orientation'],
    requiredExamples: ['scroll-area-basic', 'scroll-area-states'],
    storyId: 'components-scroll-area--docs',
    title: 'ScrollArea',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/select.docs.mdx',
    id: 'select',
    requiredControls: ['open', 'disabled', 'value'],
    requiredExamples: ['select-basic', 'select-states'],
    storyId: 'components-select--docs',
    title: 'Select',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/slider.docs.mdx',
    id: 'slider',
    requiredControls: ['label', 'value', 'disabled', 'orientation'],
    requiredExamples: ['slider-basic', 'slider-states'],
    storyId: 'components-slider--docs',
    title: 'Slider',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/switch.docs.mdx',
    id: 'switch',
    requiredControls: ['label', 'checked', 'disabled'],
    requiredExamples: ['switch-basic', 'switch-states'],
    storyId: 'components-switch--docs',
    title: 'Switch',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/toggle.docs.mdx',
    id: 'toggle',
    requiredControls: ['label', 'pressed', 'disabled'],
    requiredExamples: ['toggle-basic', 'toggle-states'],
    storyId: 'components-toggle--docs',
    title: 'Toggle',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/toggle-group.docs.mdx',
    id: 'toggle-group',
    requiredControls: ['disabled', 'multiple', 'orientation', 'value'],
    requiredExamples: ['toggle-group-basic', 'toggle-group-states'],
    storyId: 'components-toggle-group--docs',
    title: 'ToggleGroup',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/toolbar.docs.mdx',
    id: 'toolbar',
    requiredControls: ['label', 'disabled', 'orientation'],
    requiredExamples: ['toolbar-basic', 'toolbar-states'],
    storyId: 'components-toolbar--docs',
    title: 'Toolbar',
  },
] as const satisfies readonly ComponentDocsManifestEntry[];
