export const componentDocCapabilities = [
  'responsive',
  'keyboard',
  'validation',
  'overflow',
  'stateful',
  'overlay',
] as const;

export type ComponentDocCapability = (typeof componentDocCapabilities)[number];

export type ComponentDocsManifestEntry = {
  capabilities: readonly ComponentDocCapability[];
  file: string;
  id: string;
  requiredControls: readonly string[];
  requiredExamples: readonly string[];
  storyId: string;
  title: string;
};

export const componentDocsManifest = [
  {
    capabilities: ['responsive', 'keyboard', 'stateful'],
    file: 'stories/components/accordion.docs.mdx',
    id: 'accordion',
    requiredControls: ['disabledItem', 'multiple', 'value'],
    requiredExamples: ['accordion-basic', 'accordion-expansion-states'],
    storyId: 'components-accordion--docs',
    title: 'Accordion',
  },
  {
    capabilities: ['responsive'],
    file: 'stories/components/alert.docs.mdx',
    id: 'alert',
    requiredControls: ['action', 'description', 'role', 'title', 'variant'],
    requiredExamples: ['alert-basic', 'alert-variants', 'alert-role-recipe'],
    storyId: 'components-alert--docs',
    title: 'Alert',
  },
  {
    capabilities: ['responsive'],
    file: 'stories/components/avatar.docs.mdx',
    id: 'avatar',
    requiredControls: ['fallback', 'image', 'shape', 'size'],
    requiredExamples: [
      'avatar-basic',
      'avatar-image-failure',
      'avatar-size-shape-matrix',
    ],
    storyId: 'components-avatar--docs',
    title: 'Avatar',
  },
  {
    capabilities: ['responsive', 'overflow'],
    file: 'stories/components/badge.docs.mdx',
    id: 'badge',
    requiredControls: ['children', 'icon', 'size', 'variant'],
    requiredExamples: [
      'badge-basic',
      'badge-icon-and-long-label',
      'badge-size-variant-matrix',
    ],
    storyId: 'components-badge--docs',
    title: 'Badge',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/button.docs.mdx',
    id: 'button',
    requiredControls: [
      'appearance',
      'children',
      'disabled',
      'loading',
      'loadingLabel',
      'size',
      'variant',
    ],
    requiredExamples: [
      'button-basic',
      'button-appearance-variant-matrix',
      'button-sizes',
      'button-states',
    ],
    storyId: 'components-button--docs',
    title: 'Button',
  },
  {
    capabilities: ['responsive'],
    file: 'stories/components/card.docs.mdx',
    id: 'card',
    requiredControls: [
      'content',
      'description',
      'footer',
      'padding',
      'semanticElement',
      'title',
      'variant',
    ],
    requiredExamples: [
      'card-basic',
      'card-variants',
      'card-padding',
      'card-semantic-render',
    ],
    storyId: 'components-card--docs',
    title: 'Card',
  },
  {
    capabilities: ['responsive', 'overflow'],
    file: 'stories/components/code.docs.mdx',
    id: 'code',
    requiredControls: ['children', 'width'],
    requiredExamples: ['code-basic', 'code-contexts'],
    storyId: 'components-code--docs',
    title: 'Code',
  },
  {
    capabilities: ['responsive', 'overflow'],
    file: 'stories/components/code-block.docs.mdx',
    id: 'code-block',
    requiredControls: ['code', 'copyable', 'language', 'theme', 'wrap'],
    requiredExamples: ['code-block-basic', 'code-block-modes', 'code-block-copy'],
    storyId: 'components-code-block--docs',
    title: 'Code Block',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful', 'overlay'],
    file: 'stories/components/combobox.docs.mdx',
    id: 'combobox',
    requiredControls: [
      'disabled',
      'disabledOption',
      'open',
      'placeholder',
      'query',
      'selected',
    ],
    requiredExamples: [
      'combobox-basic',
      'combobox-option-states',
      'combobox-validation',
    ],
    storyId: 'components-combobox--docs',
    title: 'Combobox',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful'],
    file: 'stories/components/collapsible.docs.mdx',
    id: 'collapsible',
    requiredControls: ['disabled', 'open', 'trigger'],
    requiredExamples: ['collapsible-basic', 'collapsible-lifecycle'],
    storyId: 'components-collapsible--docs',
    title: 'Collapsible',
  },
  {
    capabilities: ['responsive'],
    file: 'stories/components/separator.docs.mdx',
    id: 'separator',
    requiredControls: ['decorative', 'orientation'],
    requiredExamples: [
      'separator-basic',
      'separator-orientations',
      'separator-semantics',
    ],
    storyId: 'components-separator--docs',
    title: 'Separator',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful'],
    file: 'stories/components/field.docs.mdx',
    id: 'field',
    requiredControls: [
      'disabled',
      'invalid',
      'label',
      'placeholder',
      'readOnly',
      'required',
      'value',
    ],
    requiredExamples: ['field-basic', 'field-field-states', 'field-validation'],
    storyId: 'components-field--docs',
    title: 'Field',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/link.docs.mdx',
    id: 'link',
    requiredControls: ['children', 'destination', 'underline', 'variant'],
    requiredExamples: [
      'link-basic',
      'link-variant-underline-matrix',
      'link-destinations',
    ],
    storyId: 'components-link--docs',
    title: 'Link',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful', 'overlay'],
    file: 'stories/components/menu.docs.mdx',
    id: 'menu',
    requiredControls: ['disabledItem', 'label', 'open'],
    requiredExamples: ['menu-basic', 'menu-item-states'],
    storyId: 'components-menu--docs',
    title: 'Menu',
  },
  {
    capabilities: ['responsive', 'keyboard', 'overflow', 'stateful', 'overlay'],
    file: 'stories/components/dialog.docs.mdx',
    id: 'dialog',
    requiredControls: ['description', 'modal', 'open', 'placement', 'size', 'title'],
    requiredExamples: [
      'dialog-basic',
      'dialog-sizes',
      'dialog-placements',
      'dialog-task-form',
    ],
    storyId: 'components-dialog--docs',
    title: 'Dialog',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful'],
    file: 'stories/components/otp-field.docs.mdx',
    id: 'otp-field',
    requiredControls: ['disabled', 'length', 'readOnly', 'required', 'value'],
    requiredExamples: [
      'otp-field-basic',
      'otp-field-length-states',
      'otp-field-validation',
    ],
    storyId: 'components-otp-field--docs',
    title: 'OTP Field',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful', 'overlay'],
    file: 'stories/components/popover.docs.mdx',
    id: 'popover',
    requiredControls: ['align', 'description', 'open', 'side', 'title'],
    requiredExamples: ['popover-basic', 'popover-sides'],
    storyId: 'components-popover--docs',
    title: 'Popover',
  },
  {
    capabilities: ['responsive'],
    file: 'stories/components/progress.docs.mdx',
    id: 'progress',
    requiredControls: ['indeterminate', 'label', 'size', 'value', 'variant'],
    requiredExamples: [
      'progress-basic',
      'progress-size-variant-matrix',
      'progress-values',
    ],
    storyId: 'components-progress--docs',
    title: 'Progress',
  },
  {
    capabilities: ['responsive'],
    file: 'stories/components/skeleton.docs.mdx',
    id: 'skeleton',
    requiredControls: ['animate', 'announced', 'height', 'label', 'shape', 'width'],
    requiredExamples: [
      'skeleton-basic',
      'skeleton-shapes',
      'skeleton-semantics',
      'skeleton-motion',
    ],
    storyId: 'components-skeleton--docs',
    title: 'Skeleton',
  },
  {
    capabilities: ['responsive'],
    file: 'stories/components/spinner.docs.mdx',
    id: 'spinner',
    requiredControls: ['decorative', 'label', 'size', 'variant'],
    requiredExamples: [
      'spinner-basic',
      'spinner-size-variant-matrix',
      'spinner-status-ownership',
    ],
    storyId: 'components-spinner--docs',
    title: 'Spinner',
  },
  {
    capabilities: ['responsive', 'keyboard', 'overflow'],
    file: 'stories/components/table.docs.mdx',
    id: 'table',
    requiredControls: ['caption', 'density', 'striped'],
    requiredExamples: ['table-basic', 'table-densities', 'table-striped-footer'],
    storyId: 'components-table--docs',
    title: 'Table',
  },
  {
    capabilities: ['responsive', 'keyboard', 'overflow', 'stateful'],
    file: 'stories/components/tabs.docs.mdx',
    id: 'tabs',
    requiredControls: [
      'activation',
      'disabled',
      'loopFocus',
      'orientation',
      'size',
      'value',
    ],
    requiredExamples: ['tabs-basic', 'tabs-sizes', 'tabs-vertical'],
    storyId: 'components-tabs--docs',
    title: 'Tabs',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful', 'overlay'],
    file: 'stories/components/toast.docs.mdx',
    id: 'toast',
    requiredControls: ['description', 'initiallyOpen', 'position', 'title', 'variant'],
    requiredExamples: [
      'toast-basic',
      'toast-variants',
      'toast-positions',
      'toast-lifecycle',
    ],
    storyId: 'components-toast--docs',
    title: 'Toast',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful', 'overlay'],
    file: 'stories/components/tooltip.docs.mdx',
    id: 'tooltip',
    requiredControls: ['align', 'content', 'open', 'side', 'trigger'],
    requiredExamples: ['tooltip-basic', 'tooltip-sides'],
    storyId: 'components-tooltip--docs',
    title: 'Tooltip',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful', 'overlay'],
    file: 'stories/components/alert-dialog.docs.mdx',
    id: 'alert-dialog',
    requiredControls: ['label', 'open', 'disabled'],
    requiredExamples: ['alert-dialog-basic', 'alert-dialog-states'],
    storyId: 'components-alert-dialog--docs',
    title: 'AlertDialog',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful', 'overlay'],
    file: 'stories/components/autocomplete.docs.mdx',
    id: 'autocomplete',
    requiredControls: [
      'placeholder',
      'open',
      'disabled',
      'readOnly',
      'required',
      'value',
    ],
    requiredExamples: [
      'autocomplete-basic',
      'autocomplete-states',
      'autocomplete-validation',
    ],
    storyId: 'components-autocomplete--docs',
    title: 'Autocomplete',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful'],
    file: 'stories/components/checkbox.docs.mdx',
    id: 'checkbox',
    requiredControls: [
      'label',
      'checked',
      'disabled',
      'indeterminate',
      'readOnly',
      'required',
    ],
    requiredExamples: ['checkbox-basic', 'checkbox-states', 'checkbox-validation'],
    storyId: 'components-checkbox--docs',
    title: 'Checkbox',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful'],
    file: 'stories/components/checkbox-group.docs.mdx',
    id: 'checkbox-group',
    requiredControls: ['disabled', 'selectedValues', 'label'],
    requiredExamples: [
      'checkbox-group-basic',
      'checkbox-group-states',
      'checkbox-group-form',
    ],
    storyId: 'components-checkbox-group--docs',
    title: 'Checkbox Group',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful', 'overlay'],
    file: 'stories/components/context-menu.docs.mdx',
    id: 'context-menu',
    requiredControls: ['label', 'open', 'disabledItem'],
    requiredExamples: ['context-menu-basic', 'context-menu-states'],
    storyId: 'components-context-menu--docs',
    title: 'ContextMenu',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful', 'overlay'],
    file: 'stories/components/drawer.docs.mdx',
    id: 'drawer',
    requiredControls: ['activeSnapPoint', 'label', 'open', 'modal', 'swipeDirection'],
    requiredExamples: ['drawer-basic', 'drawer-states'],
    storyId: 'components-drawer--docs',
    title: 'Drawer',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful'],
    file: 'stories/components/fieldset.docs.mdx',
    id: 'fieldset',
    requiredControls: ['legend', 'disabled', 'emailAlerts'],
    requiredExamples: ['fieldset-basic', 'fieldset-states'],
    storyId: 'components-fieldset--docs',
    title: 'Fieldset',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful'],
    file: 'stories/components/form.docs.mdx',
    id: 'form',
    requiredControls: ['label', 'required', 'submitLabel', 'value'],
    requiredExamples: ['form-basic', 'form-states'],
    storyId: 'components-form--docs',
    title: 'Form',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful'],
    file: 'stories/components/input.docs.mdx',
    id: 'input',
    requiredControls: [
      'placeholder',
      'disabled',
      'label',
      'readOnly',
      'required',
      'value',
    ],
    requiredExamples: ['input-basic', 'input-states', 'input-validation'],
    storyId: 'components-input--docs',
    title: 'Input',
  },
  {
    capabilities: ['responsive', 'keyboard', 'overlay'],
    file: 'stories/components/menubar.docs.mdx',
    id: 'menubar',
    requiredControls: ['disabled', 'label', 'loopFocus', 'orientation'],
    requiredExamples: ['menubar-basic', 'menubar-states'],
    storyId: 'components-menubar--docs',
    title: 'Menubar',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/meter.docs.mdx',
    id: 'meter',
    requiredControls: ['label', 'max', 'min', 'unit', 'value'],
    requiredExamples: ['meter-basic', 'meter-states'],
    storyId: 'components-meter--docs',
    title: 'Meter',
  },
  {
    capabilities: ['responsive', 'keyboard', 'overflow', 'stateful', 'overlay'],
    file: 'stories/components/navigation-menu.docs.mdx',
    id: 'navigation-menu',
    requiredControls: ['label', 'disabled', 'openSection'],
    requiredExamples: ['navigation-menu-basic', 'navigation-menu-states'],
    storyId: 'components-navigation-menu--docs',
    title: 'NavigationMenu',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful'],
    file: 'stories/components/number-field.docs.mdx',
    id: 'number-field',
    requiredControls: ['label', 'value', 'disabled', 'readOnly', 'required'],
    requiredExamples: [
      'number-field-basic',
      'number-field-states',
      'number-field-validation',
    ],
    storyId: 'components-number-field--docs',
    title: 'Number Field',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful', 'overlay'],
    file: 'stories/components/preview-card.docs.mdx',
    id: 'preview-card',
    requiredControls: ['label', 'open'],
    requiredExamples: ['preview-card-basic', 'preview-card-states'],
    storyId: 'components-preview-card--docs',
    title: 'PreviewCard',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful'],
    file: 'stories/components/radio.docs.mdx',
    id: 'radio',
    requiredControls: ['label', 'selected', 'disabled'],
    requiredExamples: ['radio-basic', 'radio-states'],
    storyId: 'components-radio--docs',
    title: 'Radio',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful'],
    file: 'stories/components/radio-group.docs.mdx',
    id: 'radio-group',
    requiredControls: ['value', 'disabled', 'readOnly', 'required'],
    requiredExamples: [
      'radio-group-basic',
      'radio-group-states',
      'radio-group-validation',
    ],
    storyId: 'components-radio-group--docs',
    title: 'Radio Group',
  },
  {
    capabilities: ['responsive', 'keyboard', 'overflow'],
    file: 'stories/components/scroll-area.docs.mdx',
    id: 'scroll-area',
    requiredControls: ['content', 'orientation'],
    requiredExamples: ['scroll-area-basic', 'scroll-area-states'],
    storyId: 'components-scroll-area--docs',
    title: 'ScrollArea',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful', 'overlay'],
    file: 'stories/components/select.docs.mdx',
    id: 'select',
    requiredControls: ['open', 'disabled', 'modal', 'readOnly', 'required', 'value'],
    requiredExamples: ['select-basic', 'select-states', 'select-validation'],
    storyId: 'components-select--docs',
    title: 'Select',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful'],
    file: 'stories/components/slider.docs.mdx',
    id: 'slider',
    requiredControls: ['label', 'value', 'disabled', 'orientation'],
    requiredExamples: [
      'slider-basic',
      'slider-states',
      'slider-range',
      'slider-form',
      'slider-validation',
    ],
    storyId: 'components-slider--docs',
    title: 'Slider',
  },
  {
    capabilities: ['responsive', 'keyboard', 'validation', 'stateful'],
    file: 'stories/components/switch.docs.mdx',
    id: 'switch',
    requiredControls: ['label', 'checked', 'disabled', 'readOnly', 'required'],
    requiredExamples: ['switch-basic', 'switch-states', 'switch-validation'],
    storyId: 'components-switch--docs',
    title: 'Switch',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful'],
    file: 'stories/components/toggle.docs.mdx',
    id: 'toggle',
    requiredControls: ['label', 'pressed', 'disabled'],
    requiredExamples: ['toggle-basic', 'toggle-states'],
    storyId: 'components-toggle--docs',
    title: 'Toggle',
  },
  {
    capabilities: ['responsive', 'keyboard', 'stateful'],
    file: 'stories/components/toggle-group.docs.mdx',
    id: 'toggle-group',
    requiredControls: ['disabled', 'loopFocus', 'multiple', 'orientation', 'value'],
    requiredExamples: [
      'toggle-group-basic',
      'toggle-group-multiple',
      'toggle-group-orientation',
    ],
    storyId: 'components-toggle-group--docs',
    title: 'ToggleGroup',
  },
  {
    capabilities: ['responsive', 'keyboard'],
    file: 'stories/components/toolbar.docs.mdx',
    id: 'toolbar',
    requiredControls: ['label', 'disabled', 'loopFocus', 'orientation'],
    requiredExamples: ['toolbar-basic', 'toolbar-states'],
    storyId: 'components-toolbar--docs',
    title: 'Toolbar',
  },
] as const satisfies readonly ComponentDocsManifestEntry[];
