import { mkdir, readFile, stat, writeFile } from 'node:fs/promises';
import { createServer, type Server } from 'node:http';
import { extname, join, relative, resolve, sep } from 'node:path';
import { type Browser, chromium, type Page } from 'playwright';

const root = resolve(import.meta.dirname, '..');
const storybookStaticDir = resolve(root, 'storybook-static');
const indexPath = resolve(root, 'storybook-static/index.json');
const reportPath = resolve(root, 'artifacts/storybook-scenario-audit/audit.json');
const auditPortEnvKey = 'STORYBOOK_AUDIT_PORT';
const auditAllEnvKey = 'STORYBOOK_AUDIT_ALL';
const storybookEntryIdKey = 'id';
const storybookEntryTitleKey = 'title';
const storybookEntryTypeKey = 'type';
const storybookEntryImportPathKey = 'importPath';
const storybookIndexEntriesKey = 'entries';
const storybookIndexStoriesKey = 'stories';
const preferredPort = Number.parseInt(process.env[auditPortEnvKey] ?? '61082', 10);
const auditAll = process.env[auditAllEnvKey] === '1';
const defaultAuditLimit = 100;
const scenarioSuffixes = [
  '--default',
  '--variants',
  '--sizes',
  '--states',
  '--examples',
  '--docs',
];
const generatedStoryMarker = 'Generated by scripts/generate-showcase-stories.ts';
const obsoleteScenarioSuffixes = [
  '--preview',
  '--composition',
  '--tokens',
  '--accessibility',
  '--playground',
];
const galleryChromeSelectors = [
  '.tinyrack-showcase-card',
  '.tinyrack-showcase-card__header',
  '.tinyrack-showcase-card__category',
  '.tinyrack-showcase-card__preview',
  '.tinyrack-showcase-card__description',
];
const curatedComponentSlugs = new Set([
  'alert',
  'badge',
  'button',
  'card',
  'checkbox',
  'dropdown',
  'input',
  'modal',
  'navbar',
  'progress',
  'radio',
  'stepper',
  'steps',
  'switch',
  'table',
  'tabs',
  'textinput',
  'toggle',
]);
const sourceAuditComponentSlugs = new Set(['button']);
const requiredStaticStorySelectors = new Map([
  ['welcome-start-here--default', '[data-storybook-welcome="true"]'],
  ['demo-mantine-product-app--default', '[data-demo-mantine="true"]'],
  ['demo-daisyui-product-app--default', '[data-demo-daisyui="true"]'],
  ['demo-starlight-docs-site--default', '[data-demo-starlight="true"]'],
]);

const contentTypes = new Map([
  ['.css', 'text/css; charset=utf-8'],
  ['.html', 'text/html; charset=utf-8'],
  ['.js', 'text/javascript; charset=utf-8'],
  ['.json', 'application/json; charset=utf-8'],
  ['.map', 'application/json; charset=utf-8'],
  ['.svg', 'image/svg+xml'],
  ['.wasm', 'application/wasm'],
]);

type StorybookEntry = {
  id: string;
  title?: string;
  type?: string;
  importPath?: string;
};

type ControlFailure = {
  id: string;
  failures: string[];
};

type AuditMetrics = {
  bodyOverflow: string;
  bodyOverflowX: string;
  bodyOverflowY: string;
  documentHeight: number;
  expectedContentPresent: boolean;
  galleryChromeCount: number;
  htmlOverflow: string;
  rootHeight: number;
  rootPresent: boolean;
  rootWidth: number;
  singleRootPresent: boolean;
  textLength: number;
};

type AuditPageResult = {
  id: string;
  scenario: string | undefined;
  title: string | undefined;
  url: string;
  metrics: AuditMetrics;
  failures: string[];
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === 'object';
}

function isStorybookEntry(value: unknown): value is StorybookEntry {
  if (!isRecord(value) || typeof value[storybookEntryIdKey] !== 'string') {
    return false;
  }

  return (
    (value[storybookEntryTitleKey] === undefined ||
      typeof value[storybookEntryTitleKey] === 'string') &&
    (value[storybookEntryTypeKey] === undefined ||
      typeof value[storybookEntryTypeKey] === 'string') &&
    (value[storybookEntryImportPathKey] === undefined ||
      typeof value[storybookEntryImportPathKey] === 'string')
  );
}

function rawEntries(indexJson: unknown) {
  const indexRecord = isRecord(indexJson) ? indexJson : {};
  const entries =
    indexRecord[storybookIndexEntriesKey] ??
    indexRecord[storybookIndexStoriesKey] ??
    indexRecord;

  return isRecord(entries) ? Object.values(entries) : [];
}

function scenarioId(storyId: string) {
  return scenarioSuffixes
    .find((suffix) => storyId.endsWith(suffix))
    ?.slice('--'.length);
}

function isGeneratedComponentEntry(entry: StorybookEntry) {
  const importPath = entry.importPath ?? '';

  return /stories\/(mantine|daisyui)\/components\//.test(importPath);
}

function obsoleteScenarioId(storyId: string) {
  return obsoleteScenarioSuffixes
    .find((suffix) => storyId.endsWith(suffix))
    ?.slice('--'.length);
}

function componentSlug(storyId: string) {
  const suffix = scenarioSuffixes.find((value) => storyId.endsWith(value));

  return suffix
    ? storyId
        .slice(0, -suffix.length)
        .replace(/^mantine-components-/, '')
        .replace(/^daisyui-components-/, '')
        .replace(/^mantine-/, '')
        .replace(/^daisyui-/, '')
    : storyId;
}

function isComponentScenario(entry: StorybookEntry) {
  return (
    scenarioSuffixes.some((suffix) => entry.id.endsWith(suffix)) &&
    isGeneratedComponentEntry(entry)
  );
}

function isRequiredStaticStory(entry: StorybookEntry) {
  return requiredStaticStorySelectors.has(entry.id);
}

function isObsoleteComponentScenario(entry: StorybookEntry) {
  return (
    obsoleteScenarioSuffixes.some((suffix) => entry.id.endsWith(suffix)) &&
    isGeneratedComponentEntry(entry)
  );
}

function readEntries(indexJson: unknown) {
  return rawEntries(indexJson)
    .filter(isStorybookEntry)
    .filter(
      (entry) =>
        entry.type === undefined || entry.type === 'story' || entry.type === 'docs',
    )
    .filter((entry) => isComponentScenario(entry) || isRequiredStaticStory(entry))
    .sort((left, right) => left.id.localeCompare(right.id));
}

function readObsoleteEntries(indexJson: unknown) {
  return rawEntries(indexJson)
    .filter(isStorybookEntry)
    .filter(isObsoleteComponentScenario)
    .sort((left, right) => left.id.localeCompare(right.id));
}

function selectEntries(entries: readonly StorybookEntry[]) {
  if (auditAll) {
    return entries;
  }

  const selected = new Map<string, StorybookEntry>();
  const add = (entry: StorybookEntry) => selected.set(entry.id, entry);

  for (const entry of entries) {
    if (isRequiredStaticStory(entry)) {
      add(entry);
    }
  }

  for (const entry of entries) {
    if (/^(mantine|daisyui)(-components)?-button--/.test(entry.id)) {
      add(entry);
    }
  }

  for (const entry of entries) {
    const scenario = scenarioId(entry.id);

    if (
      (scenario === 'sizes' || scenario === 'states') &&
      curatedComponentSlugs.has(componentSlug(entry.id))
    ) {
      add(entry);
    }
  }

  const remaining = entries.filter((entry) => !selected.has(entry.id));
  const scenarioBuckets = new Map<string, StorybookEntry[]>(
    scenarioSuffixes.map((suffix) => [
      suffix.slice('--'.length),
      [] as StorybookEntry[],
    ]),
  );

  for (const entry of remaining) {
    const scenario = scenarioId(entry.id);

    if (scenario) {
      scenarioBuckets.get(scenario)?.push(entry);
    }
  }

  while (selected.size < defaultAuditLimit) {
    let added = false;

    for (const bucket of scenarioBuckets.values()) {
      const nextEntry = bucket.shift();

      if (nextEntry) {
        add(nextEntry);
        added = true;
      }

      if (selected.size >= defaultAuditLimit) {
        break;
      }
    }

    if (!added) {
      break;
    }
  }

  return [...selected.values()].sort((left, right) => left.id.localeCompare(right.id));
}

function storySourcePath(entry: StorybookEntry) {
  const importPath = entry.importPath;

  if (!importPath || typeof importPath !== 'string') {
    return undefined;
  }

  return resolve(root, importPath.replace(/^\.\//, ''));
}

async function readControlContractFailures(
  entries: readonly StorybookEntry[],
): Promise<ControlFailure[]> {
  const sourcePaths = new Map<string, string>();

  for (const entry of entries) {
    const sourcePath = storySourcePath(entry);

    if (sourcePath && entry.importPath) {
      sourcePaths.set(sourcePath, entry.importPath);
    }
  }

  const failures: ControlFailure[] = [];

  for (const [sourcePath, importPath] of sourcePaths) {
    const source = await readFile(sourcePath, 'utf8');

    if (!source.includes(generatedStoryMarker)) {
      continue;
    }

    const entryFailures = [];

    if (!source.includes('SingleComponentStory')) {
      entryFailures.push('generated story does not use SingleComponentStory');
    }

    if (!source.includes('getShowcaseControlArgs(entry)')) {
      entryFailures.push('generated story does not use registry-backed args');
    }

    if (!source.includes('getShowcaseControlArgTypes(entry)')) {
      entryFailures.push('generated story does not use registry-backed argTypes');
    }

    const preservesDisplayName =
      /function \w+Story\(controlValues: ComponentStoryProps\)[\s\S]*?\n\w+Story\.displayName = '\w+Story';/.test(
        source,
      );

    if (!preservesDisplayName) {
      entryFailures.push('generated story does not preserve its displayName');
    }

    if (source.includes('SingleShowcaseStory')) {
      entryFailures.push('generated story still uses gallery showcase renderer');
    }

    if (source.includes('storyKind')) {
      entryFailures.push(
        'generated story still exposes storyKind instead of component controls',
      );
    }

    if (entryFailures.length > 0) {
      failures.push({
        id: importPath,
        failures: entryFailures,
      });
    }
  }

  return failures.sort((left, right) => left.id.localeCompare(right.id));
}

function createStaticServer() {
  return createServer(async (request, response) => {
    try {
      const requestUrl = new URL(request.url ?? '/', 'http://127.0.0.1');
      const requestedPath = decodeURIComponent(requestUrl.pathname);
      const filePath = resolve(
        storybookStaticDir,
        requestedPath === '/' ? 'index.html' : requestedPath.slice(1),
      );
      const relativePath = relative(storybookStaticDir, filePath);

      if (relativePath.startsWith('..') || relativePath.includes(`..${sep}`)) {
        response.writeHead(403);
        response.end('Forbidden');
        return;
      }

      const fileStat = await stat(filePath);
      const finalPath = fileStat.isDirectory()
        ? join(filePath, 'index.html')
        : filePath;
      const body = await readFile(finalPath);

      response.writeHead(200, {
        'Content-Type':
          contentTypes.get(extname(finalPath)) ?? 'application/octet-stream',
      });
      response.end(body);
    } catch {
      response.writeHead(404);
      response.end('Not found');
    }
  });
}

async function listen(server: Server) {
  const maxAttempts = 20;

  for (let attempt = 0; attempt < maxAttempts; attempt += 1) {
    const candidatePort = preferredPort + attempt;

    try {
      await new Promise<void>((resolveListen, rejectListen) => {
        const onError = (error: Error) => {
          server.off('listening', onListening);
          rejectListen(error);
        };
        const onListening = () => {
          server.off('error', onError);
          resolveListen();
        };

        server.once('error', onError);
        server.once('listening', onListening);
        server.listen(candidatePort, '127.0.0.1');
      });

      return candidatePort;
    } catch (error) {
      const code =
        error instanceof Error ? (error as NodeJS.ErrnoException).code : undefined;

      if (code !== 'EADDRINUSE' || attempt === maxAttempts - 1) {
        throw error;
      }
    }
  }

  throw new Error(`Unable to bind Storybook audit server near port ${preferredPort}`);
}

async function close(server: Server) {
  await new Promise<void>((resolveClose, rejectClose) => {
    server.close((error) => (error ? rejectClose(error) : resolveClose()));
  });
}

function expectedSelectorsFor(entry: StorybookEntry) {
  const requiredSelector = requiredStaticStorySelectors.get(entry.id);

  return requiredSelector ? [requiredSelector] : [];
}

async function readGeneratedDocsSource(page: Page, entry: StorybookEntry) {
  if (
    scenarioId(entry.id) !== 'docs' ||
    !isGeneratedComponentEntry(entry) ||
    !sourceAuditComponentSlugs.has(componentSlug(entry.id))
  ) {
    return undefined;
  }

  const showCodeButton = page.getByText('Show code', { exact: true }).first();

  try {
    await showCodeButton.waitFor({ state: 'visible', timeout: 5000 });
    await showCodeButton.click();

    const sourceBlock = page.locator('pre.prismjs').first();

    await sourceBlock.waitFor({ state: 'visible', timeout: 5000 });

    return await sourceBlock.innerText();
  } catch {
    return null;
  }
}

async function auditPage(
  page: Page,
  entry: StorybookEntry,
  auditPort: number,
): Promise<AuditPageResult> {
  const storyScenario = scenarioId(entry.id);
  const url = `http://127.0.0.1:${auditPort}/iframe.html?id=${entry.id}`;

  await page.goto(url, { waitUntil: 'networkidle' });
  await page
    .locator(
      '.tinyrack-component-story, .tinyrack-showcase-single, .tinyrack-docs-page, .tinyrack-demo-page',
    )
    .first()
    .waitFor({ state: 'attached', timeout: 5000 })
    .catch(() => {});

  const metrics = await page.evaluate<
    AuditMetrics,
    { expectedSelectors: string[]; galleryChromeSelectors: string[] }
  >(
    ({ expectedSelectors, galleryChromeSelectors }) => {
      const singleRoot = document.querySelector(
        '.tinyrack-showcase-single, .tinyrack-component-story',
      );
      const expectedRoot = expectedSelectors
        .map((selector) => document.querySelector(selector))
        .find(Boolean);
      const root =
        expectedRoot ??
        document.querySelector(
          '.tinyrack-component-story, .tinyrack-showcase-single, .tinyrack-docs-page, .tinyrack-demo-page, [data-demo-daisyui="true"]',
        );
      const rootRect = root?.getBoundingClientRect();
      const bodyStyle = window.getComputedStyle(document.body);
      const htmlStyle = window.getComputedStyle(document.documentElement);
      const visibleText = (root?.textContent ?? document.body.textContent ?? '')
        .replace(/\s+/g, ' ')
        .trim();

      return {
        bodyOverflow: bodyStyle.overflow,
        bodyOverflowX: bodyStyle.overflowX,
        bodyOverflowY: bodyStyle.overflowY,
        documentHeight: document.documentElement.scrollHeight,
        expectedContentPresent: expectedSelectors.length
          ? expectedSelectors.some((selector) => document.querySelector(selector))
          : true,
        galleryChromeCount: singleRoot
          ? galleryChromeSelectors.reduce(
              (count, selector) => count + singleRoot.querySelectorAll(selector).length,
              0,
            )
          : 0,
        htmlOverflow: htmlStyle.overflow,
        rootHeight: rootRect?.height ?? 0,
        rootPresent: Boolean(root),
        rootWidth: rootRect?.width ?? 0,
        singleRootPresent: Boolean(singleRoot),
        textLength: visibleText.length,
      };
    },
    {
      expectedSelectors: expectedSelectorsFor(entry),
      galleryChromeSelectors,
    },
  );

  const failures: string[] = [];

  if (!metrics.rootPresent) {
    failures.push('missing expected static story selector or known Storybook root');
  }

  if (metrics.singleRootPresent) {
    if (metrics.rootHeight < 32 || metrics.rootWidth < 240) {
      failures.push('component story root appears blank or too small');
    }
  } else if (metrics.textLength < 20 || metrics.rootHeight < 80) {
    failures.push('page appears blank or too small');
  }

  if (metrics.rootWidth < 900) {
    failures.push(`root width ${Math.round(metrics.rootWidth)}px is too narrow`);
  }

  if (
    (metrics.bodyOverflow === 'hidden' || metrics.bodyOverflowY === 'hidden') &&
    metrics.documentHeight > 1000
  ) {
    failures.push('body overflow is hidden');
  }

  if (!metrics.expectedContentPresent) {
    failures.push(`missing expected scenario content for ${storyScenario}`);
  }

  if (storyScenario !== 'docs' && metrics.galleryChromeCount > 0) {
    failures.push('individual story includes showcase-card gallery chrome');
  }

  const generatedDocsSource = await readGeneratedDocsSource(page, entry);

  if (generatedDocsSource === null) {
    failures.push('generated docs source code is not available');
  } else if (/<c(?:\s|\/|>)/.test(generatedDocsSource ?? '')) {
    failures.push('generated docs source uses minified component name <c />');
  }

  return {
    id: entry.id,
    scenario: storyScenario,
    title: entry.title,
    url,
    metrics,
    failures,
  };
}

async function main() {
  const indexJson: unknown = JSON.parse(await readFile(indexPath, 'utf8'));
  const entries = readEntries(indexJson);
  const obsoleteEntries = readObsoleteEntries(indexJson);
  const selectedEntries = selectEntries(entries);

  if (obsoleteEntries.length > 0) {
    const report = {
      auditedAt: new Date().toISOString(),
      auditAll,
      auditedCount: 0,
      availableCount: entries.length,
      controlFailureCount: 0,
      defaultAuditLimit,
      failures: obsoleteEntries.map((entry) => ({
        id: entry.id,
        failures: [`obsolete generated story suffix: ${obsoleteScenarioId(entry.id)}`],
      })),
      obsoleteCount: obsoleteEntries.length,
      obsoleteIds: obsoleteEntries.map((entry) => entry.id),
      port: null,
      results: [],
    };

    await mkdir(resolve(root, 'artifacts/storybook-scenario-audit'), {
      recursive: true,
    });
    await writeFile(reportPath, `${JSON.stringify(report, null, 2)}\n`);

    console.error(
      `Storybook scenario audit failed: ${obsoleteEntries.length} obsolete generated story IDs found.`,
    );
    for (const entry of obsoleteEntries.slice(0, 20)) {
      console.error(`- ${entry.id}`);
    }
    console.error(`Report: ${relative(root, reportPath)}`);
    process.exitCode = 1;
    return;
  }

  if (selectedEntries.length === 0) {
    throw new Error(
      'No Storybook component scenario entries found in storybook-static/index.json',
    );
  }

  const controlFailures = await readControlContractFailures(entries);
  const server = createStaticServer();
  let browser: Browser | undefined;
  let auditPort: number;

  auditPort = await listen(server);

  try {
    browser = await chromium.launch();
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const results: AuditPageResult[] = [];

    for (const entry of selectedEntries) {
      results.push(await auditPage(page, entry, auditPort));
    }

    const pageFailures = results.filter((result) => result.failures.length > 0);
    const failures = [
      ...controlFailures,
      ...pageFailures.map(({ id, failures: entryFailures }) => ({
        id,
        failures: entryFailures,
      })),
    ];
    const report = {
      auditedAt: new Date().toISOString(),
      auditAll,
      auditedCount: results.length,
      availableCount: entries.length,
      controlFailureCount: controlFailures.length,
      defaultAuditLimit,
      failures,
      port: auditPort,
      results,
    };

    await mkdir(resolve(root, 'artifacts/storybook-scenario-audit'), {
      recursive: true,
    });
    await writeFile(reportPath, `${JSON.stringify(report, null, 2)}\n`);

    if (failures.length > 0) {
      console.error(
        `Storybook scenario audit failed: ${failures.length} contract failures across ${results.length} audited pages.`,
      );
      for (const failure of failures.slice(0, 20)) {
        console.error(`- ${failure.id}: ${failure.failures.join('; ')}`);
      }
      console.error(`Report: ${relative(root, reportPath)}`);
      process.exitCode = 1;
      return;
    }

    console.log(
      `Storybook scenario audit passed: ${results.length} pages audited. Report: ${relative(
        root,
        reportPath,
      )}`,
    );
  } finally {
    await browser?.close();
    await close(server);
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
