import { mkdir, rm, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const marker = 'Generated by scripts/generate-showcase-stories.ts';

const registries = [
  {
    library: 'mantine',
    titlePrefix: 'Mantine',
    source: resolve(root, 'src/showcase/mantine-showcase.tsx'),
    exportName: 'mantineShowcaseEntries',
    idPrefix: 'mantine-',
  },
  {
    library: 'daisyui',
    titlePrefix: 'daisyUI',
    source: resolve(root, 'src/showcase/daisyui-showcase.tsx'),
    exportName: 'daisyUiShowcaseEntries',
    idPrefix: 'daisyui-',
  },
] as const;

type Registry = (typeof registries)[number];
type ShowcaseEntry = {
  id: string;
  name: string;
};
type StoryFilters = {
  ids: Set<string>;
  libraries: Set<string>;
};

const filters = process.argv.slice(2).reduce(
  (selection, arg) => {
    if (arg.startsWith('--library=')) {
      selection.libraries.add(arg.slice('--library='.length));
    }

    if (arg.startsWith('--id=')) {
      selection.ids.add(arg.slice('--id='.length));
    }

    return selection;
  },
  { ids: new Set<string>(), libraries: new Set<string>() } satisfies StoryFilters,
);

const hasFilters = filters.ids.size > 0 || filters.libraries.size > 0;

function componentName(name: string) {
  const cleaned = name.replace(/[^A-Za-z0-9_$]/g, '');
  const normalized = cleaned[0]?.toUpperCase() + cleaned.slice(1);
  return `${normalized || 'Showcase'}Story`;
}

function storyTitleName(name: string) {
  return name[0]?.toUpperCase() + name.slice(1);
}

async function readText(path: string) {
  return await import('node:fs/promises').then(({ readFile }) =>
    readFile(path, 'utf8'),
  );
}

function extractEntries(sourceText: string): ShowcaseEntry[] {
  return [
    ...sourceText.matchAll(
      /id: '([^']+)',\s+name: '([^']+)'([\s\S]*?)(?=\n\s+render:)/g,
    ),
  ].map(([, id = '', name = '']) => ({ id, name }));
}

function storySource({
  entry,
  registry,
}: {
  entry: ShowcaseEntry;
  registry: Registry;
}) {
  const storyComponent = componentName(entry.name);
  const titleName = storyTitleName(entry.name);
  const showcaseImports = [
    registry.exportName,
    'getShowcaseControlArgs',
    'getShowcaseControlArgTypes',
    'SingleComponentStory',
  ]
    .sort((left, right) => left.toLowerCase().localeCompare(right.toLowerCase()))
    .map((name) => `  ${name},`)
    .join('\n');

  return `// ${marker}
import '../../../src/showcase/showcase.css';
import type { Meta, StoryObj } from '@storybook/react-vite';
import type { ShowcaseControlValues } from '../../../src/showcase/index.js';
import {
${showcaseImports}
} from '../../../src/showcase/index.js';

type ComponentStoryProps = ShowcaseControlValues;

const entry = ${registry.exportName}.find(
  (showcaseEntry) => showcaseEntry.id === '${entry.id}',
);

if (!entry) {
  throw new Error('Missing showcase entry: ${entry.id}');
}

function ${storyComponent}(controlValues: ComponentStoryProps) {
  return (
    <SingleComponentStory
      controlValues={controlValues}
      entry={entry}
      library="${registry.library}"
    />
  );
}

${storyComponent}.displayName = '${storyComponent}';

const meta = {
  title: '${registry.titlePrefix}/${titleName}',
  component: ${storyComponent},
  tags: ['autodocs'],
  args: getShowcaseControlArgs(entry),
  argTypes: getShowcaseControlArgTypes(entry),
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component: entry.description,
      },
    },
  },
} satisfies Meta<typeof ${storyComponent}>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
`;
}

for (const registry of registries) {
  if (filters.libraries.size > 0 && !filters.libraries.has(registry.library)) {
    continue;
  }

  const sourceText = await readText(registry.source);
  const entries = extractEntries(sourceText);
  const selectedEntries =
    filters.ids.size > 0
      ? entries.filter(
          (entry) =>
            filters.ids.has(entry.id) ||
            filters.ids.has(entry.id.replace(registry.idPrefix, '')),
        )
      : entries;
  const outDir = resolve(root, 'stories', registry.library, 'components');

  if (!hasFilters) {
    await rm(outDir, { recursive: true, force: true });
  }

  await mkdir(outDir, { recursive: true });

  await Promise.all(
    selectedEntries.map((entry) => {
      const slug = entry.id.replace(registry.idPrefix, '');
      return writeFile(
        resolve(outDir, `${slug}.stories.tsx`),
        storySource({ entry, registry }),
      );
    }),
  );

  console.log(
    `generated ${selectedEntries.length} ${registry.library} component stories`,
  );
}
