import { defineConfig } from 'tsdown';

const entry = {
  'components/accordion/index': 'src/components/accordion/index.tsx',
  'components/alert/index': 'src/components/alert/index.tsx',
  'components/alert-dialog/index': 'src/components/alert-dialog/index.tsx',
  'components/animated-number/index': 'src/components/animated-number/index.tsx',
  'components/app-shell/index': 'src/components/app-shell/index.tsx',
  'components/autocomplete/index': 'src/components/autocomplete/index.tsx',
  'components/avatar/index': 'src/components/avatar/index.tsx',
  'components/badge/index': 'src/components/badge/index.tsx',
  'components/button/index': 'src/components/button/index.tsx',
  'components/callout/index': 'src/components/callout/index.tsx',
  'components/card/index': 'src/components/card/index.tsx',
  'components/checkbox/index': 'src/components/checkbox/index.tsx',
  'components/checkbox-group/index': 'src/components/checkbox-group/index.tsx',
  'components/code/index': 'src/components/code/index.tsx',
  'components/code-block/index': 'src/components/code-block/index.tsx',
  'components/collapsible/index': 'src/components/collapsible/index.tsx',
  'components/color-scheme-toggle/index':
    'src/components/color-scheme-toggle/index.tsx',
  'components/combobox/index': 'src/components/combobox/index.tsx',
  'components/context-menu/index': 'src/components/context-menu/index.tsx',
  'components/copy-button/index': 'src/components/copy-button/index.tsx',
  'components/dialog/index': 'src/components/dialog/index.tsx',
  'components/docs-navigation/index': 'src/components/docs-navigation/index.tsx',
  'components/docs-search/index': 'src/components/docs-search/index.tsx',
  'components/docs-shell/index': 'src/components/docs-shell/index.tsx',
  'components/document-pagination/index':
    'src/components/document-pagination/index.tsx',
  'components/drawer/index': 'src/components/drawer/index.tsx',
  'components/field/index': 'src/components/field/index.tsx',
  'components/fieldset/index': 'src/components/fieldset/index.tsx',
  'components/file-tree/index': 'src/components/file-tree/index.tsx',
  'components/form/index': 'src/components/form/index.tsx',
  'components/icon-button/index': 'src/components/icon-button/index.tsx',
  'components/input/index': 'src/components/input/index.tsx',
  'components/language-select/index': 'src/components/language-select/index.tsx',
  'components/link/index': 'src/components/link/index.tsx',
  'components/menu/index': 'src/components/menu/index.tsx',
  'components/menubar/index': 'src/components/menubar/index.tsx',
  'components/meter/index': 'src/components/meter/index.tsx',
  'components/navigation-menu/index': 'src/components/navigation-menu/index.tsx',
  'components/number-field/index': 'src/components/number-field/index.tsx',
  'components/otp-field/index': 'src/components/otp-field/index.tsx',
  'components/popover/index': 'src/components/popover/index.tsx',
  'components/preview-card/index': 'src/components/preview-card/index.tsx',
  'components/progress/index': 'src/components/progress/index.tsx',
  'components/radio/index': 'src/components/radio/index.tsx',
  'components/radio-group/index': 'src/components/radio-group/index.tsx',
  'components/scroll-area/index': 'src/components/scroll-area/index.tsx',
  'components/select/index': 'src/components/select/index.tsx',
  'components/separator/index': 'src/components/separator/index.tsx',
  'components/skeleton/index': 'src/components/skeleton/index.tsx',
  'components/slider/index': 'src/components/slider/index.tsx',
  'components/spinner/index': 'src/components/spinner/index.tsx',
  'components/steps/index': 'src/components/steps/index.tsx',
  'components/switch/index': 'src/components/switch/index.tsx',
  'components/table/index': 'src/components/table/index.tsx',
  'components/table-of-contents/index': 'src/components/table-of-contents/index.tsx',
  'components/tabs/index': 'src/components/tabs/index.tsx',
  'components/textarea/index': 'src/components/textarea/index.tsx',
  'components/toast/index': 'src/components/toast/index.tsx',
  'components/toggle/index': 'src/components/toggle/index.tsx',
  'components/toggle-group/index': 'src/components/toggle-group/index.tsx',
  'components/toolbar/index': 'src/components/toolbar/index.tsx',
  'components/tooltip/index': 'src/components/tooltip/index.tsx',
  'providers/csp/index': 'src/providers/csp/index.tsx',
  'providers/direction/index': 'src/providers/direction/index.tsx',
  'core/index': 'src/core/index.ts',
  'mdx/index': 'src/mdx/index.tsx',
} as const;

const copy = [
  { from: 'src/components/accordion/accordion.css', to: 'dist/components/accordion' },
  { from: 'src/components/alert/alert.css', to: 'dist/components/alert' },
  {
    from: 'src/components/alert-dialog/alert-dialog.css',
    to: 'dist/components/alert-dialog',
  },
  {
    from: 'src/components/animated-number/animated-number.css',
    to: 'dist/components/animated-number',
  },
  { from: 'src/components/app-shell/app-shell.css', to: 'dist/components/app-shell' },
  {
    from: 'src/components/autocomplete/autocomplete.css',
    to: 'dist/components/autocomplete',
  },
  { from: 'src/components/avatar/avatar.css', to: 'dist/components/avatar' },
  { from: 'src/components/badge/badge.css', to: 'dist/components/badge' },
  { from: 'src/components/button/button.css', to: 'dist/components/button' },
  { from: 'src/components/callout/callout.css', to: 'dist/components/callout' },
  { from: 'src/components/card/card.css', to: 'dist/components/card' },
  { from: 'src/components/checkbox/checkbox.css', to: 'dist/components/checkbox' },
  {
    from: 'src/components/checkbox-group/checkbox-group.css',
    to: 'dist/components/checkbox-group',
  },
  { from: 'src/components/code/code.css', to: 'dist/components/code' },
  {
    from: 'src/components/code-block/code-block.css',
    to: 'dist/components/code-block',
  },
  {
    from: 'src/components/collapsible/collapsible.css',
    to: 'dist/components/collapsible',
  },
  {
    from: 'src/components/color-scheme-toggle/color-scheme-toggle.css',
    to: 'dist/components/color-scheme-toggle',
  },
  { from: 'src/components/combobox/combobox.css', to: 'dist/components/combobox' },
  {
    from: 'src/components/context-menu/context-menu.css',
    to: 'dist/components/context-menu',
  },
  {
    from: 'src/components/copy-button/copy-button.css',
    to: 'dist/components/copy-button',
  },
  { from: 'src/components/dialog/dialog.css', to: 'dist/components/dialog' },
  {
    from: 'src/components/docs-navigation/docs-navigation.css',
    to: 'dist/components/docs-navigation',
  },
  {
    from: 'src/components/docs-search/docs-search.css',
    to: 'dist/components/docs-search',
  },
  {
    from: 'src/components/docs-shell/docs-shell.css',
    to: 'dist/components/docs-shell',
  },
  {
    from: 'src/components/document-pagination/document-pagination.css',
    to: 'dist/components/document-pagination',
  },
  { from: 'src/components/drawer/drawer.css', to: 'dist/components/drawer' },
  { from: 'src/components/field/field.css', to: 'dist/components/field' },
  { from: 'src/components/fieldset/fieldset.css', to: 'dist/components/fieldset' },
  { from: 'src/components/file-tree/file-tree.css', to: 'dist/components/file-tree' },
  { from: 'src/components/form/form.css', to: 'dist/components/form' },
  {
    from: 'src/components/icon-button/icon-button.css',
    to: 'dist/components/icon-button',
  },
  { from: 'src/components/input/input.css', to: 'dist/components/input' },
  {
    from: 'src/components/language-select/language-select.css',
    to: 'dist/components/language-select',
  },
  { from: 'src/components/link/link.css', to: 'dist/components/link' },
  { from: 'src/components/menu/menu.css', to: 'dist/components/menu' },
  { from: 'src/components/menubar/menubar.css', to: 'dist/components/menubar' },
  { from: 'src/components/meter/meter.css', to: 'dist/components/meter' },
  {
    from: 'src/components/navigation-menu/navigation-menu.css',
    to: 'dist/components/navigation-menu',
  },
  {
    from: 'src/components/number-field/number-field.css',
    to: 'dist/components/number-field',
  },
  { from: 'src/components/otp-field/otp-field.css', to: 'dist/components/otp-field' },
  { from: 'src/components/popover/popover.css', to: 'dist/components/popover' },
  {
    from: 'src/components/preview-card/preview-card.css',
    to: 'dist/components/preview-card',
  },
  { from: 'src/components/progress/progress.css', to: 'dist/components/progress' },
  { from: 'src/components/radio/radio.css', to: 'dist/components/radio' },
  {
    from: 'src/components/radio-group/radio-group.css',
    to: 'dist/components/radio-group',
  },
  {
    from: 'src/components/scroll-area/scroll-area.css',
    to: 'dist/components/scroll-area',
  },
  { from: 'src/components/select/select.css', to: 'dist/components/select' },
  { from: 'src/components/separator/separator.css', to: 'dist/components/separator' },
  { from: 'src/components/skeleton/skeleton.css', to: 'dist/components/skeleton' },
  { from: 'src/components/slider/slider.css', to: 'dist/components/slider' },
  { from: 'src/components/spinner/spinner.css', to: 'dist/components/spinner' },
  { from: 'src/components/steps/steps.css', to: 'dist/components/steps' },
  { from: 'src/components/switch/switch.css', to: 'dist/components/switch' },
  { from: 'src/components/table/table.css', to: 'dist/components/table' },
  {
    from: 'src/components/table-of-contents/table-of-contents.css',
    to: 'dist/components/table-of-contents',
  },
  { from: 'src/components/tabs/tabs.css', to: 'dist/components/tabs' },
  { from: 'src/components/textarea/textarea.css', to: 'dist/components/textarea' },
  { from: 'src/components/toast/toast.css', to: 'dist/components/toast' },
  { from: 'src/components/toggle/toggle.css', to: 'dist/components/toggle' },
  {
    from: 'src/components/toggle-group/toggle-group.css',
    to: 'dist/components/toggle-group',
  },
  { from: 'src/components/toolbar/toolbar.css', to: 'dist/components/toolbar' },
  { from: 'src/components/tooltip/tooltip.css', to: 'dist/components/tooltip' },
  { from: 'src/core/core.css', to: 'dist' },
  { from: 'src/internal/layer-parts.css', to: 'dist/internal' },
  { from: 'src/mdx/mdx.css', to: 'dist' },
] as const;

export default defineConfig({
  entry,
  format: 'esm',
  dts: { sourcemap: true },
  clean: true,
  fixedExtension: false,
  platform: 'neutral',
  unbundle: true,
  treeshake: true,
  sourcemap: true,
  tsconfig: './tsconfig.build.json',
  copy: [...copy],
  onSuccess: 'tsc -p tsconfig.test.json --noEmit',
});
