// Generated by scripts/generate-showcase-stories.mjs
import '../../../src/showcase/showcase.css';
import type { Meta, StoryObj } from '@storybook/react-vite';
import type { ShowcaseStoryKind } from '../../../src/showcase/index.js';
import {
  daisyUiShowcaseEntries,
  SingleShowcaseStory,
} from '../../../src/showcase/index.js';

type ComponentStoryProps = {
  storyKind?: ShowcaseStoryKind;
};

const entry = daisyUiShowcaseEntries.find(
  (showcaseEntry) => showcaseEntry.id === 'daisyui-badge',
);

if (!entry) {
  throw new Error('Missing showcase entry: daisyui-badge');
}

function BadgeStory({ storyKind = 'default' }: ComponentStoryProps) {
  return <SingleShowcaseStory entry={entry} library="daisyui" storyKind={storyKind} />;
}

const meta = {
  title: 'daisyUI/Badge',
  component: BadgeStory,
  tags: ['autodocs'],
  args: {
    storyKind: 'default',
  },
  argTypes: {
    storyKind: {
      control: 'select',
      options: ['default', 'variants', 'states'],
      description: 'Switch between component stories.',
    },
  },
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component: entry.description,
      },
    },
  },
} satisfies Meta<typeof BadgeStory>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    storyKind: 'default',
  },
};

export const Variants: Story = {
  args: {
    storyKind: 'variants',
  },
};

export const States: Story = {
  args: {
    storyKind: 'states',
  },
};
