// Generated by scripts/generate-showcase-stories.ts
import '../../../src/showcase/showcase.css';
import type { Meta, StoryObj } from '@storybook/react-vite';
import type { ShowcaseControlValues } from '../../../src/showcase/index.js';
import {
  daisyUiShowcaseEntries,
  getShowcaseControlArgs,
  getShowcaseControlArgTypes,
  SingleComponentStory,
} from '../../../src/showcase/index.js';

type ComponentStoryProps = ShowcaseControlValues;

const entry = (() => {
  const showcaseEntry = daisyUiShowcaseEntries.find(
    (candidateEntry) => candidateEntry.id === 'daisyui-diff',
  );

  if (!showcaseEntry) {
    throw new Error('Missing showcase entry: daisyui-diff');
  }

  return showcaseEntry;
})();

function DiffStory(controlValues: ComponentStoryProps) {
  return (
    <SingleComponentStory
      controlValues={controlValues}
      entry={entry}
      library="daisyui"
    />
  );
}

DiffStory.displayName = 'DiffStory';

const meta = {
  title: 'daisyUI/Diff',
  component: DiffStory,
  tags: ['autodocs'],
  args: getShowcaseControlArgs(entry),
  argTypes: getShowcaseControlArgTypes(entry),
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component: entry.description,
      },
    },
  },
} satisfies Meta<typeof DiffStory>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
