// Generated by scripts/generate-showcase-stories.ts
import '../../../src/showcase/showcase.css';
import type { Meta, StoryObj } from '@storybook/react-vite';
import type { ShowcaseControlValues } from '../../../src/showcase/index.js';
import {
  daisyUiShowcaseEntries,
  getShowcaseControlArgs,
  getShowcaseControlArgTypes,
  SingleComponentStory,
} from '../../../src/showcase/index.js';

type ComponentStoryProps = ShowcaseControlValues;

const entry = daisyUiShowcaseEntries.find(
  (showcaseEntry) => showcaseEntry.id === 'daisyui-divider',
);

if (!entry) {
  throw new Error('Missing showcase entry: daisyui-divider');
}

function DividerStory(controlValues: ComponentStoryProps) {
  return (
    <SingleComponentStory
      controlValues={controlValues}
      entry={entry}
      library="daisyui"
    />
  );
}

DividerStory.displayName = 'DividerStory';

const meta = {
  title: 'daisyUI/Divider',
  component: DividerStory,
  tags: ['autodocs'],
  args: getShowcaseControlArgs(entry),
  argTypes: getShowcaseControlArgTypes(entry),
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component: entry.description,
      },
    },
  },
} satisfies Meta<typeof DividerStory>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
