// Generated by scripts/generate-showcase-stories.ts
import '../../../src/showcase/showcase.css';
import type { Meta, StoryObj } from '@storybook/react-vite';
import type { ShowcaseControlValues } from '../../../src/showcase/index.js';
import {
  daisyUiShowcaseEntries,
  getShowcaseControlArgs,
  getShowcaseControlArgTypes,
  SingleComponentStory,
} from '../../../src/showcase/index.js';

type ComponentStoryProps = ShowcaseControlValues;

const entry = (() => {
  const showcaseEntry = daisyUiShowcaseEntries.find(
    (candidateEntry) => candidateEntry.id === 'daisyui-menu',
  );

  if (!showcaseEntry) {
    throw new Error('Missing showcase entry: daisyui-menu');
  }

  return showcaseEntry;
})();

function MenuStory(controlValues: ComponentStoryProps) {
  return (
    <SingleComponentStory
      controlValues={controlValues}
      entry={entry}
      library="daisyui"
    />
  );
}

MenuStory.displayName = 'MenuStory';

const meta = {
  title: 'daisyUI/Menu',
  component: MenuStory,
  tags: ['autodocs'],
  args: getShowcaseControlArgs(entry),
  argTypes: getShowcaseControlArgTypes(entry),
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component: entry.description,
      },
    },
  },
} satisfies Meta<typeof MenuStory>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};
